### ISSUE TITLE
Implement new design

### ISSUE THREAD

**Issue by sashuk** [sashuk/watsonc#1]
Implement new module design according to specifications

[Calypso_logo_Payoff_negativ_2.zip](https://github.com/sashuk/watsonc/files/2628753/Calypso_logo_Payoff_negativ_2.zip)

[Weltklasse_input.pdf](https://github.com/sashuk/watsonc/files/2628747/Weltklasse_input.pdf)

In order to build Vidi with `watsonc` application-wide styling, following commnad should be run:

`grunt --theme=watsonc` or `grunt production --theme=watsonc`

## Demo

https://vidi.alexshumilov.ru/app/jupiter/chemicals/?tmpl=watsonc.tmpl#osm/15/8.436/56.8911/chemicals.boreholes_time_series_without_chemicals,v:chemicals.boreholes_time_series_with_chemicals,v:sensor.sensordata_without_correction,sensor.sensordata_without_timeseries

### General

1. (+) Use only Open Sans font. Not only is the font 'Open Sans' used, but also 3 others
2. (+) Change the colors to our our colors, also red / yellow / green on symbols (+)
3. (+) Put 'titles' on the various icons when you hold them - it would create better overview in the right menu when you have opened 3 levels up to see coordinates, etc. Unless you do, the menus do not overlap (https://github.com/sashuk/watsonc/commit/688ab1b510c7d6565505d4769eb09e9c81f137e3)
4. (+) `#` in front of more texts removed
5. (+) The location icon is larger than the other card features (also it has different background color)
6. (+) You can link back to your main page watsonc.dk under the 'About' button in the right menu
7. (+) Plot is called the time series
8. (+) Placement of projects and time series in the top bar
9. (+) Lower left and right side menus (https://github.com/sashuk/watsonc/commit/0e7018889d00887de43f4a89a104e879eebb903f)

---

### Left side menu
1. (+) New menu icon https://fontawesome.com/icons/database?style=solid
2. (+) Breadcrumb, which is always visible
3. (+) 3 levels
```
|---Water level
|    |---DGU borings
|---Chemicals
|    |---Group
|    |    |---Substance
```
4. (+) Water levels and chemistry can also be just headlines
5. (+) Clear selection of which parameter you have chosen (https://github.com/sashuk/watsonc/commit/04691a2ed0c390fafcb19e69d4ec6dd9794cd2d9)

---

### Right side menu

1. (+) It would be better for a cross to replace the burger menu when it is open
2. (+) Diffuse all card features down the zoom level, so we get more air and clarity and are overwhelmed by too many buttons (https://github.com/sashuk/watsonc/commit/bb940224086bdb16f387ea31f68dabb15b943f82)
3. (+) Menu level: 'Time series' must be bold and green, and the save icon right now appears to be inactive when gray - has made a more explanatory button. (Under projects, it's ok with the save icon, but again, you increase user friendliness and lower misunderstandings by writing 'Save' project 'after the icon) (https://github.com/sashuk/watsonc/commit/bb940224086bdb16f387ea31f68dabb15b943f82)

---

Current application design:

![demo](https://user-images.githubusercontent.com/1390758/49498956-af5af200-f8a7-11e8-8fe3-12813d7b20c4.gif)

**Comment by sashuk** [comment]
@mapcentia Could you please check the translation of the following strings:

```
Time series | Tidsserier
Display two layers at once | Vis to lag samtidig
Side-by-side | Side ved side
Overlap | overlapping
Display layers | Vis lag
Found time series | Fant tidsserier
units | enheter
Uncategorized | Uncategorized
updated at | oppdatert på
No time series were created yet | Ingen tidsserier ble opprettet ennå
```

**Comment by sashuk** [comment]
@mapcentia One of the requirements in **General** says that **Placement of projects and time series in the top bar** - what should be done when user clicks **Projects** or **Time series buttons**?

**Comment by sashuk** [comment]
@mapcentia Could you please comment on these questions:

1. Could you please specify if **Tydligt markering af hvilken ”parameter” man har valgt** means that there should be a button that clears selection of parameters?
2. One of the requirements in **General** says that "Placement of projects and time series in the top bar" - is the **Projects** equal to **State snapshots**?
3. Could you please check the translation of the following strings:

```
Time series | Tidsserier
Display two layers at once | Vis to lag samtidig
Side-by-side | Side ved side
Overlap | overlapping
Display layers | Vis lag
Found time series | Fant tidsserier
units | enheter
Uncategorized | Uncategorized
updated at | oppdatert på
No time series were created yet | Ingen tidsserier ble opprettet ennå
```

**Comment by mapcentia** [comment]
@sashuk 
Overlap | overlap
Found time series | Fundne tidsserier
units | enheder
Uncategorized | Ukategoriserede
updated at | opdateret
No time series were created yet | Ingen tidsserier er oprettet endnu

**Comment by sashuk** [comment]
@mapcentia Seems like CORS headers need to be added to the `watsonc.mapcentia.com` host

![cors](https://user-images.githubusercontent.com/1390758/49430028-e87e5e00-f7e4-11e8-9754-6721a1b18c96.png)

@mapcentia 
1. Could you please specify if **Tydligt markering af hvilken ”parameter” man har valgt** means that there should be a button that clears selection of parameters?
2. One of the requirements in **General** says that "Placement of projects and time series in the top bar" - is the **Projects** equal to **State snapshots**?

**Comment by mapcentia** [comment]
@sashuk the CORS header is OK now. Its was the double header issue returning after a update yesterday.
1) No, but I'm not sure what it means. Let it be for now.
2) Yes.

**Comment by mapcentia** [comment]
@sashuk Could you move the panels down (67px)
![image](https://user-images.githubusercontent.com/3850918/49434924-a5f15d00-f7b5-11e8-8b64-6a1b7f8ded11.png)

**Comment by sashuk** [comment]
@mapcentia Thanks a lot for the feedback!

**Comment by sashuk** [comment]
@mapcentia Could you please check translations?

```
Drag and drop measurement to add it to time series | Træk og slip mål for at tilføje det til tidsserier
Remove from time series | Fjern fra tidsserier
```

**Comment by mapcentia** [comment]
@sashuk 
Drag and drop measurement to add it to time series | Træk og slip målinger for at tilføje det til tidsserier

**Comment by sashuk** [comment]
@mapcentia Design was implemented, the complete set of performed actions according to the provided PDF is in the issue description.
