### ISSUE TITLE
In IE11 nothing shows in pop-up, when clicking on a marker

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#10]
Is there a work-around?
![image](https://user-images.githubusercontent.com/3850918/50154790-acf69000-02ca-11e9-86b9-e2adbbe1f86a.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/f24f9faaee02e07e124ceb254faef9615c8182fc

IE11 does not support `Object.values()`, so this command was replaced
