### ISSUE TITLE
Split dialog in two views with independent scroll bars

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#14]
When having a lot of measurements you may need to scroll down:
![image](https://user-images.githubusercontent.com/3850918/51969068-c1a27800-2473-11e9-9931-d18133c2bb81.png)
The Plot widget will then disappear out of the view:
![image](https://user-images.githubusercontent.com/3850918/51969186-134b0280-2474-11e9-8932-9f734a342f27.png)
Solultion: Split the view in two with independent scroll bars

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/609d708cacaf759f6a6e124f873a5fe9c4339efa

![scroll](https://user-images.githubusercontent.com/1390758/52037209-51761e00-2569-11e9-8fef-58399ee58c1d.gif)
