### ISSUE TITLE
Link on borehole number in dialog

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#15]
Create a link on the pop-up dialog for `chemicals.boreholes_time_series_with_chemicals`
![image](https://user-images.githubusercontent.com/3850918/51969334-6c1a9b00-2474-11e9-99ae-1f15d89342d1.png)
Link template: http://data.geus.dk/JupiterWWW/borerapport.jsp?dgunr={$boreholeno}

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/bcb1853f186a7a2ea26709199d2545ecdfd085f8

![links](https://user-images.githubusercontent.com/1390758/52037230-5dfa7680-2569-11e9-8233-9c2e692af2a7.gif)

**Comment by mapcentia** [comment]
@sashuk When the dialog changes (eg. new plot) the link disappear:
![image](https://user-images.githubusercontent.com/3850918/52164156-506df980-26ed-11e9-83ba-636d35480d07.png)
![image](https://user-images.githubusercontent.com/3850918/52164158-5368ea00-26ed-11e9-97c3-46f72ae505b4.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/24bc5104918659bc8ea8b17da83b4391aeace10b

![links2](https://user-images.githubusercontent.com/1390758/52187436-710e8e80-2868-11e9-8afa-da9aaf7408f7.gif)
