### ISSUE TITLE
Store selected chemical in State

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#16]
Store selected chemical in State.
![image](https://user-images.githubusercontent.com/3850918/51983153-3daeb700-2498-11e9-8bad-8caddc721463.png)

**Comment by sashuk** [comment]
Solving the **performance** issue along - when any state snapshot is applied or visited via link, the vector layers are fetching 2000 features (the actual features fetch limit) instead of regularly fetching 100-150 ones in a regular mode.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/b1777070090d36ab0fae4ddca97e172f956f7efc

![chemical](https://user-images.githubusercontent.com/1390758/52193886-4e8e6c80-288c-11e9-9b22-2e50204a6fc1.gif)
