### ISSUE TITLE
Plots has to be updated with current data, when Snapshot is applied

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#17]
As for now I believe the Snapshot stored plots also stores s snapshot of the data?
Some data er rapidly coming in and a restored Snapshot should show current data.

**Comment by sashuk** [comment]
@mapcentia Yes, the `MenuComponent` stores the measurements data in snapshots, which are lately stored in state, so it is possible to track if the snapshot data became stale. The update tracking will be implemented.

https://github.com/sashuk/watsonc/blob/a2a1562e2a3afeee2f2dd34de59df4abcf8c9145/browser/components/MenuComponent.js#L101

**Comment by sashuk** [comment]
@mapcentia Could you please tell if there is any borehole which is constantly updating to test this issue in real conditions?

**Comment by mapcentia** [comment]
@sashuk The boreholes from `sensor.sensordata_with_correction` (the blue ones) are updating constantly

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
There are two scenarios when plot data should be updated:
- when the state snapshot is applied and some plots contains stale data;
- when page is refreshed and not stored in state snapshot plots have stale data;

**Comment by sashuk** [comment]
@mapcentia The syncing of data is implemented in https://github.com/sashuk/watsonc/commit/176b0631a19e268300d93b1db7fa3d2440f2aa58

The **plot**, which is stored in the **state snapshot**, has the measurement location identifier (the borehole identifier, chemical and the intake indexes) and the actual measurement cached data. The synchronization of data is performed every time the vector layers are loaded - the `watsonc` module proposes plots component to update its data, as the fresh one just came in:
- if the fresh data has the specific measurement, used in one of the plots, it is updated and the displayed plot is changed;
- if the fresh data does not have the specific measurement, used in one of the plots, then the plot uses the cached data as usual.

The screencast below shows how cached plot updates whenever the fresh data is available

![synced](https://user-images.githubusercontent.com/1390758/53073336-b5658400-3522-11e9-974b-c3f1871a0a47.gif)

However, this mechanism can be extended:
1. Every time the state snapshot is applied, measurements used in its plots are requested even if they are not loaded and displayed on the map as the vector ones;
2. Every time the plot sees that its cached data in state snapshot is stale, it updates the actual state snapshot with new data.

@mapcentia Should the **(1)** and **(2)** be implemented as well?

**Comment by sashuk** [comment]
@mapcentia Having a big number of **time series** open, the update process (when every measurement is checked for staleness by requesting the backend) can take too much time.
Assuming that the state snapshot should be updated only manually, then auto-update (which will be performed being hidden from the user) should not be used (so, the user will not be aware of changes in state snapshot that he has stored before).

The `auto-update-data-on-feature-availability` mechanism was implemented.
