### ISSUE TITLE
Mark which boreholes are used in plots

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#18]
When using a measurement from a borehole in a plot, then "highlight" it on the map.

Could we use Leaflet Circle Markers instead of Marker icons in the vector layers? This is related to https://github.com/sashuk/vidi/issues/204, but it may be possible to change from Circle Marker to Marker when choosing a measurement?

**Comment by sashuk** [comment]
@mapcentia Sure, it is possible! So, when the measurement is chosen (the panel with available measurements and plots is shown) its marker should be changed to the Circle Marker one?

**Comment by mapcentia** [comment]
@sashuk The idea is not to use the water drop shaped markers at all, because it takes more ressources in the browser. So the water drop shaped markers should just be plain CircleMarkers (svg). When a borehole is used in a plot, when the CircleMarker should change style (color and size).

**Comment by sashuk** [comment]
@mapcentia So, am I correct that if the point (chemicals or water measurements layer) is used at least in one plot, then it changes color? If it is not used, then it stays default blue color of the CircleMarker?

**Comment by mapcentia** [comment]
@sashuk Yes. But of course it still have to change to the two color split icon when selecting a chemical:
![image](https://user-images.githubusercontent.com/3850918/52042169-c3843e00-253c-11e9-8417-42a842ebca26.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if I am correct concerning requirements:
- both vector layers initially are displayed as CircleMarkers of two different colors (chemicals and water measurements). If the measurement presents in at least in one of plots then it has slighlty different representation (the opacity could be `0`, for example);
- when measurement is clicked, the modal is shown and the measurement CircleMarker is replaced with Icon (the waterdrop-shaped one as before);
- when modal is shown, those plots in the plot panel that include this measurement are highlighted.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/a44e9c200a28dcdae23435291c895228492ca864

Concerning the performance -the case when all measurements are displayed as SVG icons (same as CircleMarker, as it uses SVG as well) was compared with the case when all measurements are displayed using the regular marker (AwesomeMarker):


Request | SVG (CircleMarker, SVG Icon) | Regular marker (AwesomeMarker)
--------- | ------------ | -------------
Chemicals (~2.5 MB of data) | 106ms | 86ms
Water levels (~2.2 MB of data) | 269ms | 776ms


So, using the SVG for measurements is better in terms of performance, so this way was implemented.

Demo:
![measurements](https://user-images.githubusercontent.com/1390758/53640964-8c529b00-3c68-11e9-9096-5f4819d97f8f.gif)
