### ISSUE TITLE
WatsonC Water level plot throws error then ploting two boreholes. And plot doesn't show anything

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#2]
![image](https://user-images.githubusercontent.com/3850918/49080896-68d11c00-f245-11e8-8156-c3a4fe50ef6f.png)

**Comment by mapcentia** [comment]
@sashuk I still don't see any ploting with the new layer:
![image](https://user-images.githubusercontent.com/3850918/49154692-63450600-f319-11e8-9892-14d3010aab01.png)

**Comment by sashuk** [comment]
@mapcentia You are exactly right! Layer data can be processed following way:
1. keep data until new portion of it is loaded after map extent change (currently used);
2. accumulate all loaded data (used in plots) until page reload, so the plots populated after page load will always have theirs data;
3. accumulate all loaded data (used in plots) and store it in `localStorage`, single data entries will be updated upon load of these entries; implement controls for clearing the stored data; implement storing of data using the `stateSnapshots` module;

Right now data is stored until page reload and `stateSnapshots` keep only references to measurements for plots, not the data itself. Should the **(3)** option be implemented?

**Comment by sashuk** [comment]
> @sashuk done

Thanks, the `sensor.sensordata_without_correction` is now dynamic

**Comment by mapcentia** [comment]
@sashuk We go for option 3

**Comment by sashuk** [comment]
@mapcentia Got it, thanks! I will close this issue and create new one with the actual feature request then (#3).
