### ISSUE TITLE
New startup wizard

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#20]
General change: The layer tree to the left should be removed.

When Vidi starts the user should be presented with a modal view:
![image](https://user-images.githubusercontent.com/3850918/54877739-c99ee880-4e22-11e9-8f84-22f25e3fba86.png)

For now there should be two options: Start New Project and Open Existing Project.

Start New Project:
![image](https://user-images.githubusercontent.com/3850918/54877764-4df16b80-4e23-11e9-8e0d-2266ded3ef60.png)
To the left the user can check off which layers should be switched on. For now there is two option: sensor.sensordata_without_correction and chemicals.boreholes_time_series_without_chemicals
To the right the user can pick one chemical to display. This this corresponds to check a chemical in the layer tree in the current version. The chemicals should be listed a shown in the image (without the move handle). When clicking one, it should be highlighted. Also the user should be able to filter the chemicals.

Open Existing Project:
![image](https://user-images.githubusercontent.com/3850918/54877828-631aca00-4e24-11e9-8077-732da6a6e9bc.png)
Here the user can "play" a snapshot. Only the title, date and play button should be displayed. 

There must be a button the user can click to get back to the modal view. E.g. if the user wants to pick another chemical.

**Comment by sashuk** [comment]
@mapcentia Could you please clarify on these issues:
1. What if to display the right chemicals list depending on the layers checked in the left menu? If none of the layers are checked, then selecting the chemical will still enable the chemicals layer (in order to load data);
2. When the chemical is chosen and highlighted, is the modal hidden right away (however, the button at the left corner of the header can dynamically display something like `Open the menu (current chemical: Nitrat)` and when it is clicked, the menu modal is shown again)?
3. Is the list of projects the same as displayed in the state snapshots module? When the user clicks the regular `Projects` map control, should he still be able to create state snapshots?
4. When the menu modal is displayed, should it have the backdrop, so the user can not interact with map and map controls until he selects the layer and chemical / opens the specific project?
5. At what condition user can just view the map without selecting the chemical? Probably the user can still just close the modal window (opposite to **(4)**) and view measurements?

**Comment by sashuk** [comment]
@mapcentia For now, the following is implemented:
- the `StateSnapshots` component is refactored in the form of a separate file, so it is re-used in `watsonc` module (https://github.com/sashuk/vidi/commit/62de00bedd3a71c12f9f05a1bce2d119a42e8158); 
- the overall modal dialog;

What is left to implement:
- the actual selection of layer and chemical.

![watsonc](https://user-images.githubusercontent.com/1390758/54898125-f972ec80-4f05-11e9-8142-9276a5a674d1.gif)

**Comment by mapcentia** [comment]
@sashuk 

1. The chemical list is a brutto list containing all possible chemicals. So if user choose `sensor.sensordata_without_correction`, which only has "Water level", and pick something like Nitrat, the symbols would just be grey.  But in the future the `sensor.sensordata_without_correction` may have other chemicals. So in that sense both layers are chemical layers. You should not be able to continue if you don't choose a layer to the left. 
2. When chemical is chosen and highlighted and at least one layer is chosen a Continue labelled button should appear, which will hide the modal view. And yes, you should be able to show the modal again the way you describe. 
3. The list of projects in the startup modal should only display the title and date. The regular Projects map control should work as it does now and the user should be able to create new snape shots.
4. Yes, the modal should block the interface. A transparent backdrop would be fine.
5. I'm not sure if the user should be able to continue without choosing a chemical. For starters could you add a "None" pseudo chemical, so the user has to make a active decision about chemicals?

**Comment by sashuk** [comment]
@mapcentia Thank you for the clarification!

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/548d6fe08b4afa30a581c110098cb905e1d4c89b

![intromodal](https://user-images.githubusercontent.com/1390758/55564004-91a07b00-5729-11e9-9a33-9acf1376f9b7.gif)

**Comment by mapcentia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New startup wizard](https://trello.com/c/TTyHnnSH/65-new-startup-wizard)

**Comment by ksnwatsonc** [comment]
![Start et nyt projekt – 1](https://user-images.githubusercontent.com/50231643/57127980-4f06a880-6d92-11e9-831c-073093c17f5f.png)

- Button "Registrer nye data" needs to be removed from the wizard. It will be introduced later on. 
- The greyed out boxes, are feautures that will come later on as well.
- Water level category in the right side should be inside same scroller as the chemicals.
- There is no need for the "Continue without"-button. "Fortsæt"(continue)-button can be clicked with or without selected chemicals.

**Comment by sashuk** [comment]
@mapcentia @ksnwatsonc Could you please specify what for are the layer switchers on the right side if the water level is in the list with chemicals by default? Assuming that now clicking on the first layer shows all chemicals and in order to show the water level, the second layer has to be clicked.

**Comment by JacobBirk** [comment]
@sashuk The left side specifies the layer sources. For now the 

1. DGU boringer (boreholes timeserie.... & waterlevel) 

2. Andre vandstandsstationer (Sensor data with ...)

The right side select data type. if (1) is checked alle chemicals and waterlevel (from jupiter database) should be selectable. 
If (2) is checked only waterlevel from sensor should be selectable.
if (1) and  (2) is checked waterlevel contains both waterlevel form jupiter database and sensor data

Does that make sense ?

Nice meeting you Aleksandr :-)

**Comment by sashuk** [comment]
@JacobBirk Hello, Jacob, nice to meet you too!:)

The explanation is great, requirements were implemented in https://github.com/sashuk/watsonc/commit/d3b33d9cfa77fc142dc9920879f810b900dbe145

![design](https://user-images.githubusercontent.com/1390758/57145527-f963e780-6df5-11e9-886f-1fa6dd993372.gif)
