### ISSUE TITLE
New "Dashboard" for plots

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#21]
Instead of displaying plots in the right side panel, they should be displayed in a "Dashboard", which can be in docked, half extented and full extented mode:
![image](https://user-images.githubusercontent.com/3850918/55394533-cea91980-553f-11e9-81b0-b04307610c03.png)
![image](https://user-images.githubusercontent.com/3850918/55394726-3b241880-5540-11e9-8b23-a28a22f50491.png)
![image](https://user-images.githubusercontent.com/3850918/55394750-46774400-5540-11e9-9ba0-0f937bac5537.png)
The Dashboard use a grid layout max two cells wide. It should be possible to drag-order the cells.

**Comment by sashuk** [comment]
Current progress:

![timeseries](https://user-images.githubusercontent.com/1390758/55665797-c884a700-5877-11e9-9cdc-27d5fa632ae6.gif)

**Comment by mapcentia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New "Dashboard" for plots](https://trello.com/c/e9ylnN0v/67-new-dashboard-for-plots)

**Comment by sashuk** [comment]
@mapcentia  Implemented in https://github.com/sashuk/watsonc/commit/566dc13fa4c6ee8d5b1b7bbbf1f688191566e2a4 and https://github.com/sashuk/watsonc/commit/4c746c59348a6812e824bbbb6646e3cfe41ce55d

![dashboard](https://user-images.githubusercontent.com/1390758/55699237-7751f000-59fc-11e9-8f11-c1eb709e855d.gif)
