### ISSUE TITLE
New style for WatsonC dashboard

### ISSUE THREAD

**Issue by sashuk** [sashuk/watsonc#23]
![Web 1920 – 1](https://user-images.githubusercontent.com/1390758/55694471-f2a8a700-59e6-11e9-9f92-8fc0fe34133a.png)

![Web 1920 – 3](https://user-images.githubusercontent.com/1390758/55694472-f3413d80-59e6-11e9-8b68-040c78a7ed31.png)

![Web 1920 – 4](https://user-images.githubusercontent.com/1390758/55694473-f3413d80-59e6-11e9-9fbe-ea3386469363.png)

![Web 1920 – 5](https://user-images.githubusercontent.com/1390758/55694475-f3413d80-59e6-11e9-9c86-41051feb98b5.png)

**Comment by sashuk** [comment]
@mapcentia Could you please clarify on following moments:

- what should happen when `Register new data` is pressed (seems like it has to be the third screen in startup modal, as there is also `Register new data` menu item)?
- is there any specification on how `Search` should work (the search scope, any advanced filtering, the UI of search results)?
- is there any specification on how `Starred` should work for boreholes (the starred boreholes listing panel UI, filtering)?
- is it required to style scroll bars in the startup dialog?

Current progress:

![startupmodal](https://user-images.githubusercontent.com/1390758/56289816-691a7700-6154-11e9-9816-22b2b9f7298d.gif)

**Comment by mapcentia** [comment]
@sashuk 
`Register new data` is a future feature. Leave that out for now.
`Search` (up in the right corner) is an address search, which I'll implement. It will just center the map on the wanted address.
`Starred` I'm not sure. I'll add an new issue regarding this one.
styled scroll bars? No, leave that be.

**Comment by sashuk** [comment]
@mapcentia Could you please specify if chemicals in the left column should have colored circles near them and if they do, is color assigned as when the chemical is selected?

Current progress (`Register new data` and `Starred` features were postponed):

![design](https://user-images.githubusercontent.com/1390758/56351730-5c535d00-6200-11e9-8c28-6b6f28274e3c.gif)

**Comment by mapcentia** [comment]
@sashuk I'm not sure what you about "chemicals in the left column"?

**Comment by sashuk** [comment]
@mapcentia Please see the screenshot:

![55694472-f3413d80-59e6-11e9-8b68-040c78a7ed31](https://user-images.githubusercontent.com/1390758/56577128-d028a780-65fc-11e9-9ca8-a42e91668fae.png)

**Comment by mapcentia** [comment]
@sashuk  Yes, I see now. These symbols are what you see for a single borehole in the map after you have selected a chemical. The idea is that you also see the symbols up front when you click on a borehole. The symbols are create here: https://github.com/sashuk/watsonc/blob/master/browser/index.js#L956-L1087 Maybe you can extract the function and put it in a module and reuse it?

**Comment by sashuk** [comment]
@mapcentia Sure, thanks for the clarification!

**Comment by sashuk** [comment]
@mapcentia Color indications were added in https://github.com/sashuk/watsonc/commit/4d10bb1c4832aa0bd6e0682e64122d6944428315

![style](https://user-images.githubusercontent.com/1390758/56659603-2286c880-66d0-11e9-86fc-084aae88d3d8.gif)
