### ISSUE TITLE
When vector layer is switched off by zoom out it will not be switched on agian when zoom in

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#25]
Also if you start zoomed out, the vector will not switch on when zooming in

![Peek 2019-04-29 10-30](https://user-images.githubusercontent.com/3850918/56884387-e9e94500-6a69-11e9-9e8d-0a5df465a61b.gif)

**Comment by mapcentia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When vector layer is switched off by zoom out it will not be switched on agian when zoom in](https://trello.com/c/At8XfOPR/74-when-vector-layer-is-switched-off-by-zoom-out-it-will-not-be-switched-on-agian-when-zoom-in)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/663b9251b708ca5ecf588297f33b5e20c83fd8d5

![zoom](https://user-images.githubusercontent.com/1390758/56954340-218ee480-6b71-11e9-8e04-a1a1102fadba.gif)
