### ISSUE TITLE
Some adjustments to info window

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#26]
![image](https://user-images.githubusercontent.com/3850918/56921547-572ac380-6ac6-11e9-9bd3-56843bfd5e89.png)

**Comment by mapcentia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adjustments to info window](https://trello.com/c/tNfgvcPb/73-adjustments-to-info-window)

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/582f12e6b36775fc68a96f1d0292dd9f3318df9e

![designissues](https://user-images.githubusercontent.com/1390758/56954204-d07ef080-6b70-11e9-8018-5d21ad24a7f0.gif)
