### ISSUE TITLE
Plot canvas should be responsive, so it fills out the space in the grid cell

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#27]
Now it seems that plots have a fixed width

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/52ec44819451df2980ebd5d3a6f35a68da0edba0

![responsive](https://user-images.githubusercontent.com/1390758/57095756-2ce73900-6d46-11e9-9585-634e9084964e.gif)
