### ISSUE TITLE
Plots should use native legend

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#28]
It seems, that the legend is something created outside Plotly? Is there a reason for this?

From Vidi:
![image](https://user-images.githubusercontent.com/3850918/57034703-8c631d00-6c50-11e9-889d-60329c175276.png)

Native legend:
![image](https://user-images.githubusercontent.com/3850918/57034733-9e44c000-6c50-11e9-965e-deb62ae09de2.png)

**Comment by sashuk** [comment]
@mapcentia Is used to contain controls for deleting the measurement, so now it can be surely made as a native one.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/52ec44819451df2980ebd5d3a6f35a68da0edba0

![watsonc](https://user-images.githubusercontent.com/1390758/57095772-396b9180-6d46-11e9-8b89-b060b2624954.gif)
