### ISSUE TITLE
Right-side menu

### ISSUE THREAD

**Issue by ksnwatsonc** [sashuk/watsonc#29]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/50231643/57129244-1963be80-6d96-11e9-8098-fca9c1e71f03.gif)

All functions should be contained in the right-side menu. The top left menu "vælg data" should be removed. These data can instead be reached from the right side menu under "datakilder- og typer".

"Min konto" links to the admin-page of Calypso.

The video shows how to choose a previously created set of "tidsserier" and "målinger".

**Comment by ksnwatsonc** [comment]
This link show most of the interactions in the right menu. Please ask if you have any questions or concerns :)

https://xd.adobe.com/view/a9a827c7-6c98-4e1d-6333-6da2ad4868d1-df99/

**Comment by ksnwatsonc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Højre-side menu](https://trello.com/c/rLfUpErr/76-h%C3%B8jre-side-menu)

**Comment by JacobBirk** [comment]
A few extra comments:
"datakilder og -typer" opens 
![Screenshot 05-03-2019 14 24 23](https://user-images.githubusercontent.com/50234893/57137132-3789e880-6daf-11e9-8443-bcad7e4142af.png)
== same at bottom part of upstart wizard 
Admin-page has the address: https://admin.calypso.watsonc.dk/ 
Dashboard contains Timeseries, profiles and tables (later). New, hide/show, delete of these is controlled from the right side menu and not from the dashboard

**Comment by JacobBirk** [comment]
@sashuk @ksnwatsonc @mapcentia 
We (WatsonC) are learning how to struture issues and I think we have to brake et into smaller issues. Kristians interactice proto type is good for overview, but contains to much.
Here is som additional comments to the right side menu
![image](https://user-images.githubusercontent.com/50234893/57184574-a6edfe00-6ebd-11e9-9722-dbb40e728d5b.png)

All the round icons is only vidi items.
**"datakilder and - types"** links to "data menu" - Screenshot in previous comment.    
**Projekter** opens project manager in right side menu
**Tidsserier** opens timeseries manager in right side menu. 
**Profiles** opens profile manager in right side menu
**Tabeller** i a datalist (table) that kan be added to the dashboard af timeseries and profiles - **to be implemented later.
The menu structure for tidsserier, profiler and tabeller is similar: New item is generated, old items are listet, item is added og removed from dashboard.
Se github items

**Comment by sashuk** [comment]
@JacobBirk Breaking into small issues is indeed a great idea! The current issue was implemented in https://github.com/sashuk/watsonc/commit/9e76d3ed353612d605994e645a03d8a937e4bdbe, getting to the `Timeseries` menu.

Demo:

![mainmenu](https://user-images.githubusercontent.com/1390758/57211517-1de8db00-7013-11e9-9b66-22b46df2fda7.gif)
