### ISSUE TITLE
Store plot data

### ISSUE THREAD

**Issue by sashuk** [sashuk/watsonc#3]
Process layer data in following way: accumulate all loaded data (used in plots) and store it in localStorage, single data entries will be updated upon load of these entries; implement controls for clearing the stored data; implement storing of data using the `stateSnapshots` module.

**Comment by sashuk** [comment]
@mapcentia The data caching was implemented (measurements data is stored in the actual plot object, so it is automatically stored in state snapshots and in local `state`) in https://github.com/sashuk/watsonc/commit/0f76465ee285b81e4e7465fca27ed405391b0d42

Right now we can see the time when the measurement data was actually added to the plot, however, the data needs to stay relevant. Could you please specify if the measurements data **can be possibly altered in some point of future**?

If **yes**, then
- manual update mechanism will be implemented (for example, user can trigger the update for every measurement)
- automatic update mechanism will be implemented (it will probablt be too expensive in terms of performance, as app will have to compare huge measurements objects)

If **no**, then
- measurement data will just stay with plot forever

![cacheddata](https://user-images.githubusercontent.com/1390758/49274434-59570a80-f4b3-11e8-80d9-72bc46b21409.gif)

**Comment by mapcentia** [comment]
@sashuk Data will change. Especially the new layer, which is updatered within seconds. Its live measurements on water levels.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks! The automatic data update will be implemented then.

**Comment by sashuk** [comment]
@mapcentia Right now data can be updated only by manually reloading the vector layer (some kind of constant connection for tracking updates using the WebSockets technology can be developed for `layerTree` later for tracking data updates on server). 

Am I correct that for now the update for measurements should be implemented only when the layer is reloaded? In order to update data that is stored only in plot and have not been loaded via vector layer before, there could be a button that changes the map extent to the extent that ensures the layer data update.

**Comment by mapcentia** [comment]
@sashuk On reload of layer is fine. I'll check with the client if something like live data over web socket is necessary

**Comment by sashuk** [comment]
@mapcentia Thank you!

**Comment by sashuk** [comment]
@mapcentia Data update (for plot measurements) was implemented in https://github.com/sashuk/watsonc/commit/7350ba9b92b927e29e844d7a69b592e14fac7c49
