### ISSUE TITLE
Timeserie menu

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#30]
@sashuk @mapcentia 
![image](https://user-images.githubusercontent.com/50234893/57184712-c128db80-6ebf-11e9-9d7b-bf6a6604458e.png)
Left Check box add/remove timeseries to the dashboards 
Radio button highlights  items in the map that are on the plot

**Comment by sashuk** [comment]
@JacobBirk Could you please specify if the actual time series should be listed in the red area, and controls for managing time series in the blue area? Also could you please specify what is expected when the user clicks the checkbox in the blue area (how time series can be "enabled")?

![demo](https://user-images.githubusercontent.com/1390758/57211827-3f969200-7014-11e9-9b83-03c5e697aa05.png)

**Comment by JacobBirk** [comment]
@sashuk Yes,  timeseries are shown as graphs in the red window and controlled (add/removed) form the blue window.
Marked checkbox in the blue area add timeserie to the red window - 5 marked ==> 5 TS in the blue window

**Comment by sashuk** [comment]
@JacobBirk Thanks a lot!

**Comment by JacobBirk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bottom dialog](https://trello.com/c/1aUqHv6j/77-bottom-dialog)

**Comment by JacobBirk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Timeserie menu](https://trello.com/c/NA4gXR5z/78-timeserie-menu)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk The Timeseries menu was implemented in https://github.com/sashuk/watsonc/commit/0471758c07dc40afd89ea87055acebf73e3583a3 and https://github.com/sashuk/watsonc/commit/8309d303ccf7d5216fbe9011ba20595c904c169b

![demo](https://user-images.githubusercontent.com/1390758/57288066-62e04080-70eb-11e9-8947-b2dec19153a2.gif)
