### ISSUE TITLE
Bottom dialog

### ISSUE THREAD

**Issue by sashuk** [sashuk/watsonc#31]

**Comment by sashuk** [comment]
@JacobBirk Could you please specify what types of data the bottom dialog should contain (according to the https://xd.adobe.com/view/a9a827c7-6c98-4e1d-6333-6da2ad4868d1-df99/screen/1ffe2b04-9749-4be5-b3b8-9a7894aba1d9/Tabeller-Mine-tabeller-tilf-j it contains at least time series and some kind of configuration objects)? Should these objects be all sortable between each other? What does the `+` button do at the very top of the dialog?

**Comment by JacobBirk** [comment]
@sashuk 
The bottom dialog contains:

- Timeseries (as now)

- Profiles

- Tables/data lists **(implemented later**). The list would eg. contains a list of sensor stations with eg. warning levels of waterlevel.

![image](https://user-images.githubusercontent.com/50234893/57212578-75bc1d80-6fe4-11e9-82a3-1ec05f5e07e3.png)

Forget the + bottom
Your current layout is fine.
Substitute Timeseries with Calypso dashboard
![image](https://user-images.githubusercontent.com/50234893/57213447-21666d00-6fe7-11e9-9837-1ed46cd5a0d9.png)

Nice if you could make a bottom that switch between matrix and row view

**Comment by JacobBirk** [comment]
@sashuk @mapcentia 
We or Martin will provide more timeserie plot specifikations later

**Comment by sashuk** [comment]
@JacobBirk Thanks for the clarification, looking forward to new information!

**Comment by JacobBirk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bottom dialog](https://trello.com/c/1aUqHv6j/77-bottom-dialog)

**Comment by sashuk** [comment]
@JacobBirk As time series and profiles are now displayed in the Dashboard, could you please specify the requirements for the `Tables/data lists`?

**Comment by JacobBirk** [comment]
We are not ready with the tables jet.

In the dashboard ee would like an option to switch between matrix and row view - eg. one or to plots across the page.

You are welcome to start on issue 42 and 33😉




Jacob
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: Thursday, May 30, 2019 10:03:56 AM
Til: sashuk/watsonc
Cc: Jacob Birk Jensen; Mention
Emne: Re: [sashuk/watsonc] Bottom dialog (#31)


@JacobBirk<https://github.com/JacobBirk> As time series and profiles are now displayed in the Dashboard, could you please specify the requirements for the Tables/data lists?

**Comment by sashuk** [comment]
@JacobBirk Got it, thanks! Should this issue include tables or it can be closed and the tables will be in the separate one?

Matrix and row view implemented in https://github.com/sashuk/watsonc/commit/db117431043d158450f82efd645f8d98acf9d73a

![views](https://user-images.githubusercontent.com/1390758/58712099-7fbe1a00-83f2-11e9-9b45-07142c9641cc.gif)

**Comment by JacobBirk** [comment]
Looks perfect👍
Yes close the issue.  Tables will be in later issue

Jacob
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: Friday, May 31, 2019 4:22:06 PM
Til: sashuk/watsonc
Cc: Jacob Birk Jensen; Mention
Emne: Re: [sashuk/watsonc] Bottom dialog (#31)


@JacobBirk<https://github.com/JacobBirk> Got it, thanks! Should this issue include tables or it can be closed and the tables will be in the separate one?

Matrix and row view implemented in db11743<https://github.com/sashuk/watsonc/commit/db117431043d158450f82efd645f8d98acf9d73a>

[views]<https://user-images.githubusercontent.com/1390758/58712099-7fbe1a00-83f2-11e9-9b45-07142c9641cc.gif>

**Comment by sashuk** [comment]
@JacobBirk Great, thanks! Closing the issue.
