### ISSUE TITLE
Webpage title

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#32]
@mapcentia 
Webpage title: Calypso by WatsonC instead of Mapcentia Vidi
Calypso icon instead of Mapcentia Vidi icon
Simplify url (if possible) eg.:  (https://map.calypso.watsonc.dk/app/jupiter/chemicals,sensor/?session=s%3AWg2bdG-pvYglCl6Gl_1LFSOEIPT5-aGk.wMGz7HwK4molfgOKClDJOD2mrZYFhgysSxnSENXxkgQ#geodk.bright/8/10.07/56.8495/sensor.sensordata_without_correction,v:sensor.sensordata_with_correction,chemicals.boreholes_time_series_without_chemicals)

**Comment by JacobBirk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Titel på siden skal hedde Calypso by WatsonC inkl logo og ikke Mapcentia Vidi](https://trello.com/c/IKaUN7PI/49-titel-p%C3%A5-siden-skal-hedde-calypso-by-watsonc-inkl-logo-og-ikke-mapcentia-vidi)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if it is okay if the Vidi will have a title tag set to `Loading...` and missing favicon by default, so when the actual Vidi bundle is loaded, the title and favicon are replaced depending on inner logic (so it can be `MapCentia Vidi` by default or `Calypso by WatsonC`)?

**Comment by sashuk** [comment]
@mapcentia @JacobBirk When Vidi is built with `grunt --theme=watsonc ...` the **title** and **favicon** are replaced (implemented in https://github.com/sashuk/vidi/commit/8d850104c6c043cd00bd0221bcc10f8d45f56026).

![page](https://user-images.githubusercontent.com/1390758/57290670-72ae5380-70f0-11e9-97b3-09c3395e371c.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk The URL can be shortened in terms of layer names - as layer names are pretty long, they can be "aliased" with the shorter ones, like

```
v:sensor.sensordata_with_correction = v:sensors
sensor.sensordata_without_correction = sensors
v:chemicals.boreholes_time_series_with_chemicals = v:chemicals
chemicals.boreholes_time_series_without_chemicals) = chemicals
```

The idea is to have these "aliased" names in URL, but the Vidi internals will still operate the regular long layer names. Is this an acceptable variant or shorting the URL? However, this adds an additional level of complexity to the application with a not very significant gain in URL length, so should this be implemented?

**Comment by sashuk** [comment]
@mapcentia @JacobBirk The URL can be shortened in terms of layer names - as layer names are pretty long, they can be "aliased" with the shorter ones, like

```
v:sensor.sensordata_with_correction = v:sensors
sensor.sensordata_without_correction = sensors
v:chemicals.boreholes_time_series_with_chemicals = v:chemicals
chemicals.boreholes_time_series_without_chemicals) = chemicals
```

The idea is to have these "aliased" names in URL, but the Vidi internals will still operate the regular long layer names. Is this an acceptable variant or shorting the URL? However, this adds an additional level of complexity to the application with a not very significant gain in URL length, so should this be implemented?

**Comment by JacobBirk** [comment]
@sashuk I don't know much about it, but I have seen examples where the full address is hidden and shown as eg https://map.calypso.watsonc.dk in the browser.

If this is not possible or time consuming, your solution is fine :-)

**Comment by mapcentia** [comment]
@JacobBirk @sashuk Its not possible to hide the URI path and parameters and only show the hostname. The Safari browser does it, but its a browser thing, which Apple has decided on.

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Then closing the issue (actually the URL can be without any parameters, as application state will be stored in memory only, but it will require some changes across multiple modules of Vidi).
