### ISSUE TITLE
Add Find Me button

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#34]

**Comment by sashuk** [comment]
@mapcentia Should the button have access to actual geolocation of user and showing it on the map? Where should it be located?

**Comment by JacobBirk** [comment]
@sashuk @mapcentia 
yes and yes - located here 
![image](https://user-images.githubusercontent.com/50234893/57289752-41b42b80-70bc-11e9-952b-c9796ea22979.png)
Remove project and timeserie icon (access by right menu)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk `Find me` button was added, two other buttons were removed (implemented in https://github.com/sashuk/watsonc/commit/40cf5fd0bce8e047f3a2a6d9e038a7d8b1734135).


![location](https://user-images.githubusercontent.com/1390758/57294053-fff5a600-70f8-11e9-803d-c0c204cedafa.gif)
