### ISSUE TITLE
Profilegeneration - select relevant layeres 

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#35]
@mapcentia After drawing the profile the relevant "layers" has to be selected.
Ole's Script now looks into one npy file (FOHM_layers_v2.npy) and we need to extend this with more layer files.

For all layer packages we will provide you with configuration file containing:
**Title: FOHM
Subtitle: Geologisk model for Jylland
Type (geology, terrain, potential): geology
layerfile: FOHM_layers_v2.npy
layerinfo: inventory.txt
Dataextend: FOHM.shp
Upperleft x:
Upperleft y:
Cell size: 100
Nx:
Ny:**

After drawing of profile are completed you will need to look into all "dataextend" files and list  Layer packages that is present along profile with stationing as
![image](https://user-images.githubusercontent.com/50234893/57359196-67523b00-7177-11e9-8054-ee44dac9b9ba.png)

The intersected layer packages is show in right side menu (new issue is made)

After selection in GUI the python script input 

'{"coordinates": [[565977, 6372779], [567447, 6370030], [569000, 6369000]], "DGU_nr": ["  6.   37A", "  6.   37B", "  6.   64B", "  6.  413", "  6.   64A", "  6.  414", "  6.  835", "  6.  412", "  6.  783", "  6.  751", "  6.  931", "  6.  954", "  6.  955"], "Profile_depth": -80}'

is expanded with

FOHM_config.txt
Start_stationing
End_stationing

for selected Layer packages

eg: model_1_config.txt, 100, 420, model_2_config.txt, 0, 730, model_3_config.txt, 320, 620, 

config file  and polygon files:
[FOHM_config.txt](https://github.com/sashuk/watsonc/files/3156336/FOHM_config.txt)
[FOHM_extent.zip](https://github.com/sashuk/watsonc/files/3156337/FOHM_extent.zip)

**Comment by JacobBirk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Profile generation - select layers](https://trello.com/c/R6tjOcwI/79-profile-generation-select-layers)

**Comment by JacobBirk** [comment]
@mapcentia Attached is a zip file with another layer
[Potentialekort_Aalborg_extend.zip](https://github.com/sashuk/watsonc/files/3156614/Potentialekort_Aalborg_extend.zip)

**Comment by JacobBirk** [comment]
@sashuk Have a look at this and see if you need input from Martin

**Comment by sashuk** [comment]
@JacobBirk Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Could you please specify if there is any script for detecting stationing values for intersections between the profile and shapefile layers (just curious, I've started on it anyway)?

Also, what are stationing values when the profile crosses the model polygon two and more times like in the picture below - I assume the output will be `..., model_N_config.txt, B, C, model_1_config.txt, D, E, ...`?

Also, does the model file (`SHP`) always contains one polygon?

![edge_case](https://user-images.githubusercontent.com/1390758/57683853-266e9080-7667-11e9-8cbf-c9d476a283e0.png)

---

The overall profile generation workflow:

![profile_drawing](https://user-images.githubusercontent.com/1390758/57674877-ffa65f00-7652-11e9-98cf-d68f5bff5185.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Is there any repo to store the Python scripts and layer data or maybe the one should be created?

The script for scanning the configuration files:

```python
# -*- coding: utf-8 -*-
"""
Created on Tue May 14 2019
@author: https://github.com/mapcentia
"""

import os
from pprint import pprint
import shapefile
import psycopg2
import pandas.io.sql as sqlio
from shapely.geometry import Point, LineString, Polygon, shape
import pandas as pd
import json
import sys

# {"coordinates": [[565977, 6372779], [567447, 6370030], [569000, 6369000]], "configFolder": "data"}

if __name__ == "__main__":
    inputdata = json.loads(sys.argv[1])

    result = []
    
    fileRoot = "/home/admin/watsonc/";

    # Scan folder for configurations
    configFiles = [];
    localDataFolder = fileRoot + inputdata['configFolder']
    if os.path.isdir(localDataFolder):
        for file in os.listdir(localDataFolder):
            if file.endswith("_config.txt"):
                configFiles.append(os.path.join(localDataFolder, file))
    else:
        raise Exception("Provided folder " + localDataFolder + " does not exist")

    # Select configurations with existing dataextend properties
    processedConfigurationFiles = []
    for x in configFiles:
        processedConfigurationFile = {}
        configurationFile = open(x, "r")
        configurationFile = configurationFile.readlines()
        for line in configurationFile:
            lineSplit = line.split(":")
            if len(lineSplit) == 2:
                lineSplit[0] = lineSplit[0].strip()
                lineSplit[1] = lineSplit[1].strip()
                processedConfigurationFile[lineSplit[0]] = lineSplit[1]
        processedConfigurationFiles.append(processedConfigurationFile);

    # Check for intersection of provided line with found model polygons
    pkter = inputdata['coordinates']
    inputLine = LineString(pkter)

    intersectingModels = []
    for x in processedConfigurationFiles:
        for key, value in x.items():
            if key == "Dataextend":
                localShape = shapefile.Reader(os.path.join(localDataFolder, value))
                feature = localShape.shapeRecords()[0]
                first = feature.shape.__geo_interface__
                modelPoly = shape(first)

                # -------- @todo-----------
                # ! Get stationing values !
                # -------------------------

                if inputLine.intersects(modelPoly):
                    localResult = {}
                    localResult['title'] = x['Title']
                    localResult['subtitle'] = x['Subtitle']
                    localResult['type'] = x['Type (geology, terrain, potential)']
                    localResult['layerinfo'] = x['layerinfo']
                    localResult['intersectionSegments'] = []
                    intersectingModels.append(localResult)

    pprint(intersectingModels)
```

Result:

```json
[{
  "intersectionSegments": [],
  "layerinfo": "inventory.txt",
  "subtitle": "Geologisk model for Jylland",
  "title": "FOHM",
  "type": "geology"
}]
```

**Comment by JacobBirk** [comment]
@sashuk 
I don't think we have any, but it might be a good idea. 
Could you explain what it is and the benifit ?

**Comment by JacobBirk** [comment]
> @mapcentia @JacobBirk Could you please specify if there is any script for detecting stationing values for intersections between the profile and shapefile layers (just curious, I've started on it anyway)?
> Also, what are stationing values when the profile crosses the model polygon two and more times like in the picture below - I assume the output will be ..., model_N_config.txt, B, C, model_1_config.txt, D, E, ...?
> Also, does the model file (SHP) always contains one polygon?
> 
> 
> The overall profile generation workflow:

@sashuk there is properly script for detection intersections - we haven't looked for one - should we?

Yes the output model_N_config.txt, B, C, model_N_config.txt, D, E is perfect

only one polygon per shp file

**Comment by JacobBirk** [comment]
@sashuk 
https://user-images.githubusercontent.com/1390758/57674877-ffa65f00-7652-11e9-98cf-d68f5bff5185.png
look perfect to me

**Comment by sashuk** [comment]
@JacobBirk Thank you very much for clarifications!

The benefit of the script is that it automates the adding of new models (as long as they have properly constructed `*_config.txt` file). 
The benefit of the repository (the private one, for example) would be to keep all data in one place and to track all changes as the regular CVS system. For example, when adding a new model it will be enough just to upload it to the repository and update codebase on all instances of `watsonc` afterwards.

**Comment by JacobBirk** [comment]
@sashuk 
Sound good

**Comment by sashuk** [comment]
> @sashuk there is properly script for detection intersections - we haven't looked for one - should we?

@JacobBirk Am I correct that when the profile is available, some script has to find all intersections of the actual profile `LineString` with all models `Polygons`? However, this is not just a fact of intersection (`true` or `false`), but actual stationing values like in the image above (these values, as I understand, mean the actual distance on the `LineString` from the beginning of the profile to the actual intersection point), so there should be a way to find these stationing values. There are ideas how to do it, just wanted to make sure that I understand the task correctly.

@sashuk Yes exactly

**Comment by sashuk** [comment]
@JacobBirk Thanks, great! Then next thing I will start on this part of the script. By the way, are `stationing values` measured in meters or any other unit?

@sashuk yes meter

**Comment by sashuk** [comment]
Input geodata (black one is a profile line)

![input](https://user-images.githubusercontent.com/1390758/57766664-59358900-773a-11e9-86ce-8c38a225af28.png)

**Comment by JacobBirk** [comment]
@sashuk The FOHM.shp covers Jylland & Fyn (2/3 of denmark) and the "potentiale_aal…..shp" is the one en the middle.

Output is only the FOHM_config.txt, line_start, line_end

**Comment by sashuk** [comment]
@JacobBirk Thank for the information! Am I correct that the profile can be anywhere inside of Denmark, so every time all `SHP`'s should be checked for intersection with the profile?

@sashuk Yes, all shp files should be checked

**Comment by sashuk** [comment]
Test cases for intersection script

![testing](https://user-images.githubusercontent.com/1390758/57847339-cca5cc00-7808-11e9-8cd1-675dba70cf37.png)

Latest script version:

```python
# -*- coding: utf-8 -*-
"""
Created on Tue May 14 2019
@author: https://github.com/mapcentia
"""

import os
from pprint import pprint
import shapefile
import psycopg2
import pandas.io.sql as sqlio
from shapely.geometry import Point, LineString, Polygon, shape
import pandas as pd
import json
import sys
from pyproj import Proj, transform

# {"coordinates": [[565977, 6372779], [567447, 6370030], [569000, 6369000]], "configFolder": "data"}

LOG = False

def transformPoint(x, y):
    inProj = Proj(init='epsg:25832')
    outProj = Proj(init='epsg:4326')
    x2, y2 = transform(inProj, outProj, x, y)
    return x2, y2

if __name__ == "__main__":
    inputdata = json.loads(sys.argv[1])

    result = []
    
    fileRoot = "/home/admin/watsonc/";

    # Scan folder for configurations
    configFiles = [];
    localDataFolder = fileRoot + inputdata['configFolder']
    if os.path.isdir(localDataFolder):
        for file in os.listdir(localDataFolder):
            if file.endswith("_config.txt"):
                configFiles.append(os.path.join(localDataFolder, file))
    else:
        raise Exception("Provided folder " + localDataFolder + " does not exist")

    # Select configurations with existing dataextend properties
    processedConfigurationFiles = []
    for x in configFiles:
        processedConfigurationFile = {}
        configurationFile = open(x, "r")
        configurationFile = configurationFile.readlines()
        for line in configurationFile:
            lineSplit = line.split(":")
            if len(lineSplit) == 2:
                lineSplit[0] = lineSplit[0].strip()
                lineSplit[1] = lineSplit[1].strip()
                processedConfigurationFile[lineSplit[0]] = lineSplit[1]
        processedConfigurationFiles.append(processedConfigurationFile);

    # Check for intersection of provided line with found model polygons
    pkter = inputdata['coordinates']
    inputLine = LineString(pkter)

    currentPolygon = 0
    intersectingModels = []
    for x in processedConfigurationFiles:
        for key, value in x.items():
            if key == "Dataextend":
                if LOG:
                    pprint("Polygon " + str(currentPolygon))

                localShape = shapefile.Reader(os.path.join(localDataFolder, value))
                feature = localShape.shapeRecords()[0]
                firstModelPolygon = feature.shape.__geo_interface__
                modelPoly = shape(firstModelPolygon)

                if inputLine.intersects(modelPoly):
                    lineStartIsInsideOfThePolygon = False
                    firstPoint = Point(pkter[0])
                    if modelPoly.contains(firstPoint):
                        lineStartIsInsideOfThePolygon = True

                    if LOG:
                        pprint("Line starts inside of the polygon: " + str(lineStartIsInsideOfThePolygon))

                    previousPointIsInsideOfThePolygon = lineStartIsInsideOfThePolygon
                    summarizedAbsoluteLength = 0
                    summarizedInsideLength = 0

                    intersectionSegments = []
                    i = 0
                    while i < len(pkter):
                        # Iterating over line vertices
                        if i > 0:
                            if LOG:
                                pprint("Profile segment " + str(i))

                            profileSegment = LineString([pkter[i - 1], pkter[i]])

                            if LOG:
                                pprint(transformPoint(pkter[i - 1][0], pkter[i - 1][1]))
                                pprint(transformPoint(pkter[i][0], pkter[i][1]))

                            currentPoint = Point(pkter[i])
                            currentPointIsInsideOfThePolygon = modelPoly.contains(currentPoint)

                            # If (N-1) point is outside and the N point is inside (or vice-versa), then need
                            # to get the intersection and finish the current stationing segment
                            if currentPointIsInsideOfThePolygon != previousPointIsInsideOfThePolygon:
                                previousPointIsInsideOfThePolygon = currentPointIsInsideOfThePolygon
                                intersectionPoint = False

                                j = 0
                                while j < len(firstModelPolygon['coordinates']):
                                    k = 0
                                    while k < len(firstModelPolygon['coordinates'][j]):
                                        polygonSide = False
                                        if k == 0:
                                            polygonSide = (firstModelPolygon['coordinates'][j][len(firstModelPolygon['coordinates'][j]) - 1], firstModelPolygon['coordinates'][j][k])
                                        else:
                                            polygonSide = (firstModelPolygon['coordinates'][j][k - 1], firstModelPolygon['coordinates'][j][k])

                                        modelPolygonSegment = LineString([polygonSide[0], polygonSide[1]])
                                        intersection = profileSegment.intersection(modelPolygonSegment);
                                        if intersection.wkt != "GEOMETRYCOLLECTION EMPTY":
                                            if LOG:
                                                pprint("Line segment " + str(i) + " intersects polygon segment " + str(k) + " (model " + str(j) + ")")
                                            intersectionPoint = intersection
                                        k += 1
                                    j += 1

                                if intersectionPoint == False:
                                    raise Exception("The intersection was detected, but the actual intersection point was not found")
                                else:
                                    # Add first half length to the previous stationing segment, add second half length to the next stationing segment
                                    totalSegmentLength = profileSegment.length
                                    splitProportion = abs(intersectionPoint[0] - pkter[i - 1][0]) / abs(pkter[i - 1][0] - pkter[i][0])
                                    beforeCrossingLength = (summarizedInsideLength + totalSegmentLength * splitProportion)
                                    afterCrossingLength =  (summarizedInsideLength + totalSegmentLength * (1 - splitProportion))

                                    if currentPointIsInsideOfThePolygon == True:
                                        summarizedInsideLength = afterCrossingLength
                                    else:
                                        intersectionSegments.append((summarizedAbsoluteLength - summarizedInsideLength), summarizedAbsoluteLength + beforeCrossingLength)
                                        summarizedInsideLength = 0
                            else:

                                # --- ! ---
                                # Process the case than single line segment barely crosses the polygon part, so there
                                # can be multiple stationing segments
                                # --- ! ---

                                # Last line segment case
                                if (i == (len(pkter) - 1) and previousPointIsInsideOfThePolygon):
                                    intersectionSegments.append((summarizedAbsoluteLength - summarizedInsideLength, summarizedAbsoluteLength))

                                if currentPointIsInsideOfThePolygon == True:
                                    summarizedInsideLength += profileSegment.length

                                if LOG:
                                    pprint("Adding full segment length (segment is " + str(profileSegment.length) + "m, total length is " + str(summarizedInsideLength) + "m)")

                            summarizedAbsoluteLength += profileSegment.length
                        i += 1

                    localResult = {}
                    localResult['title'] = x['Title']
                    localResult['subtitle'] = x['Subtitle']
                    localResult['type'] = x['Type (geology, terrain, potential)']
                    localResult['layerinfo'] = x['layerinfo']
                    localResult['intersectionSegments'] = intersectionSegments
                    intersectingModels.append(localResult)
                else:
                    currentPolygon += 1

                    # Line is completely inside of the poluygon
                    firstPoint = Point(pkter[0])
                    if modelPoly.contains(firstPoint):
                        localResult = {}
                        localResult['title'] = x['Title']
                        localResult['subtitle'] = x['Subtitle']
                        localResult['type'] = x['Type (geology, terrain, potential)']
                        localResult['layerinfo'] = x['layerinfo']
                        localResult['intersectionSegments'] = [(0, inputLine.length)]
                        intersectingModels.append(localResult)

    pprint("Overall result")
    pprint(intersectingModels)
```

Result for demo data:

```javascript
[{
  'intersectionSegments': [(0, 3118)],
  'layerinfo': 'inventory.txt',
  'subtitle': 'Geologisk model for Jylland',
  'title': 'FOHM',
  'type': 'geology'}]
```

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Today tests were written for cases presented above, but I think that that the script should process all the cases possible, like *(I)* in the image below (when the single line segment is crossing polygon multiple times, so there are multiple stationing points).

![testing (2)](https://user-images.githubusercontent.com/1390758/57944005-32c54880-7908-11e9-9fc2-7220fb3c1f0c.png)

The script and tests:

[script_zip.zip](https://github.com/sashuk/watsonc/files/3192394/script_zip.zip)

**Comment by JacobBirk** [comment]
Looks like you are covering all possible cases 👍

Jacob

________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: fredag, maj 17, 2019 7:01 PM
Til: sashuk/watsonc
Cc: Jacob Birk Jensen; Mention
Emne: Re: [sashuk/watsonc] Profilegeneration - select relevant layeres (#35)


@mapcentia<https://github.com/mapcentia> @JacobBirk<https://github.com/JacobBirk> Today tests were written for cases presented above, but I think that that the script should process all the cases possible, like (I) in the image below (when the single line segment is crossing polygon multiple times, so there are multiple stationing points).

[testing (2)]<https://user-images.githubusercontent.com/1390758/57944005-32c54880-7908-11e9-9fc2-7220fb3c1f0c.png>

The script and tests:

script_zip.zip<https://github.com/sashuk/watsonc/files/3192394/script_zip.zip>

**Comment by sashuk** [comment]
The script was finished, getting to linking it with the `watsonc` module

[script.zip](https://github.com/sashuk/watsonc/files/3207065/script.zip)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk The full intersection-search was implemented in https://github.com/sashuk/watsonc/commit/fe97a985d96c5b4c20ee9234fe8521df2a779ef7 and in Python scripts attached to this comment. Overall:
- `watsonc` builds the profile
- finds what shapefiles intersect with the profile
- finds what are stationing points values for each intersected file
- builds the list of intersected files in the UI

Demo:

![intersection](https://user-images.githubusercontent.com/1390758/58269809-e0c66c00-7dba-11e9-9cc2-b55ef99c6ae4.gif)

Scripts:

[scripts.zip](https://github.com/sashuk/watsonc/files/3213218/scripts.zip)
