### ISSUE TITLE
Profile generation - right menu

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#36]
See interactive prototype and details below
![AdobeXD0805201910_39_19](https://user-images.githubusercontent.com/50234893/57362967-46daae80-7180-11e9-99d3-029e7f469ccd.gif)

Select old profile or make new (Opret ny profil)
![image](https://user-images.githubusercontent.com/50234893/57361744-615f5880-717d-11e9-967d-0a8196a3390b.png)

Click "Opret ny profil" 
Adjust buffer 
Adjust profile bottom (Juster profil bund) - default (-100) ==> input to profile script

 '{"coordinates": [[565977, 6372779], [567447, 6370030], [569000, 6369000]], "DGU_nr": ["  6.   37A", "  6.   37B", "  6.   64B", "  6.  413", "  6.   64A", "  6.  414", "  6.  835", "  6.  412", "  6.  783", "  6.  751", "  6.  931", "  6.  954", "  6.  955"], **"Profile_depth": -80**}'
![image](https://user-images.githubusercontent.com/50234893/57361841-abe0d500-717d-11e9-990d-f778c1c71414.png)

Draw (tegn profil)

Continue (fortsæt) => operations as described ind issue #35 
![image](https://user-images.githubusercontent.com/50234893/57362350-eac35a80-717e-11e9-82f9-9d2d2286794c.png)

Select layers:
![image](https://user-images.githubusercontent.com/50234893/57362403-0c244680-717f-11e9-8629-f477163ba30e.png)
Layers marked "Geology" listed below divider and all other listet above

Name profile
Click "opret" generate => call script with selected layers are arguments to profile script as described in #35

**Comment by JacobBirk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [profile generation - Right menu](https://trello.com/c/KPbulO7R/80-profile-generation-right-menu)

**Comment by JacobBirk** [comment]
@sashuk Have a look at this and see if you need input from Martin

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Could you please give information on the following questions:
- should profiles be stored via `key-value` storage?
- is the profile an actual geometry `LineString` AND the selected intersected layers?

**Comment by JacobBirk** [comment]
@sashuk 
I'm not into the details about how, but profiles should be stored.

A stored profile contains:
Line, intersected layers, buffer, depth, and profile (or should that be formed from 
"Line, intersected layers, buffer, depth"?

**Comment by sashuk** [comment]
@JacobBirk You are totally correct, the profile is generated from line and buffer. Thanks for the clarification!

**Comment by sashuk** [comment]
@JacobBirk Could you please specify:
- if the `profiletool.py` should be called like `profiletool.py "{'coordinates': [[565977, 6372779], [567447, 6370030]], 'DGU_nr': ['  6.   37A', '  6.   37B'], 'Profile_depth': -80}"  Potentialekort_Aalborg_config.txt 0 120 FOHM_config.txt 170 290`?
- if the result of `profiletool.py` execution should be stored as well with the `Line, intersected layers, buffer and depth`?

Currently, the application is able to retrieve the boreholes names (that are intersected by the profile), the stationing points and selected layers, so it can provide the `Potentialekort_Aalborg_config.txt 0 120 FOHM_config.txt 170 290` part, but according to the provided `profiletool.py` script it seems like it should be refactored to work not only with the `FOHM_layers_v2.npy` (as you have mentioned in https://github.com/sashuk/watsonc/issues/35, but just to make sure).

**Comment by JacobBirk** [comment]
@sashuk 
The profiletool.py is not ready for multible layer packages yet. The output would only be based om FORHM_layers_v2.npy no matter what the input are

**Comment by sashuk** [comment]
@JacobBirk So, should I modify the `profiletool.py` or the version that supports multiple layer packages already exists?

**Comment by JacobBirk** [comment]
No, we will adjust the script.  You can use the the existing script with the additional arguments

Jacob
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: Friday, May 24, 2019 5:40:29 PM
Til: sashuk/watsonc
Cc: Jacob Birk Jensen; Mention
Emne: Re: [sashuk/watsonc] Profile generation - right menu (#36)


@JacobBirk<https://github.com/JacobBirk> So, should I modify the profiletool.py or the version that supports multiple layer packages already exists?

**Comment by sashuk** [comment]
@JacobBirk Thank you for the information!

**Comment by olemunch** [comment]
Hi @sashuk 
I think we should inklude all arguments in the JSON object like this:
In the example I added two overlapping sections for each layer/model. The size of "layers" should bed the same as the size of "overlap" 

'{"coordinates": [[565977, 6372779], [567447, 6370030]], "DGU_nr": [" 6. 37A", " 6. 37B"], "Profile_depth": -80, "layers":["Potentialekort_Aalborg_config.txt","FOHM_config.txt"],"overlap":[[[0,170], [250,500]],[[120,290],[800,1000]]]}'

<img width="369" alt="ArgumentsProfileTool" src="https://user-images.githubusercontent.com/51031638/58403942-3cffe900-8064-11e9-9936-c3590fe59d65.png">

**Comment by sashuk** [comment]
@olemunch Got it, thanks! I will use this format then.

**Comment by sashuk** [comment]
@JacobBirk Could you please specify:
- when the profile is checked (the `Title` column in profiles list), does it mean that it should be shown in the dashboard panel?
- when the radio is selected (the second column in profiles list), should the original profile `LineString` be built on the map or the profile polygon should be built instead?

Current progress:

![profiles](https://user-images.githubusercontent.com/1390758/58432554-82b0c600-80e5-11e9-9aeb-1dde6660cb51.gif)

**Comment by JacobBirk** [comment]
@sashuk Yes the profile should be added to the dashboard
2. question: I don't know if I understand, but I think both the line and polyson should be build and the profile added to the dashboard when selected an old stored profile

**Comment by mapcentia** [comment]
@sashuk Could add the Python scripts to this repo and hardcode the script path? It'll make it easier to checkout.

**Comment by sashuk** [comment]
@JacobBirk Thanks you very much!
@mapcentia Sure, I will do it! Should the data be stored in the repo as well (the `FOHM_layers_v2.npy` is around 700MB, for example)?

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Last changes:
- scripts now reside in https://github.com/sashuk/watsonc/tree/master/scripts (the configuration files for module reside in https://github.com/sashuk/watsonc/blob/master/config/config.js.sample);
- the module for managing profiles is implemented and linked with the backend;
- the module for managing profiles allows showing the original profile and the buffered one;
- created profiles are integrated with the `Dashboard`.

Implemented in https://github.com/sashuk/watsonc/commit/dd9e9987f87b81c7075e7907f30ded072930baf6 and https://github.com/sashuk/watsonc/commit/b7e06ea9dcc0628785307bd9f88e05a17646d540

Demo:

![profiles](https://user-images.githubusercontent.com/1390758/58504925-4c934500-81be-11e9-902b-13e4c76decf9.gif)

**Comment by olemunch** [comment]
Hi that is BRILLIANT @sashuk 

When you generate a profile graph could you ad this last part below to remove the autoscale button. The problem is, that we use 2 y-axis which must be aligned. Pushing the autoscale button will result in a wrong z-location of boreholes.

Plotly.plot('graph', data, layout,{modeBarButtonsToRemove: ['autoScale2d']})

**Comment by sashuk** [comment]
@olemunch Thank you very much! The `autoscale` was removed in https://github.com/sashuk/watsonc/commit/4bd9107a1cdaeff342efa2837d82e28bda55f423

Demo:

![autoscale](https://user-images.githubusercontent.com/1390758/58528399-eaabfd00-8208-11e9-9132-27bd0f740934.png)

**Comment by JacobBirk** [comment]
@sashuk Super cool :-)
