### ISSUE TITLE
GUI adjustments to 080519 test version

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#37]
@sashuk @mapcentia 
When new timeseries is generated from here
![image](https://user-images.githubusercontent.com/50234893/57369085-0a617f80-718d-11e9-9036-c40e59fb62db.png)
they must be automatically turned on in the dashboard and placed at first position 

**Right menu:**
- titles are missing  
![image](https://user-images.githubusercontent.com/50234893/57370014-60cfbd80-718f-11e9-8dac-7137ba2ea2c6.png)
Title this "datakilder og -typer" => opens 
![image](https://user-images.githubusercontent.com/50234893/57370235-f1a69900-718f-11e9-84ea-1ada912eb6b8.png)

**Dashboard**
- Remove title &save
- Dashboard is not accessible when right menu is open 
![image](https://user-images.githubusercontent.com/50234893/57369728-958f4500-718e-11e9-926b-4139073c92a9.png)
resize dashboard when right menu are open or move arrows to the middle of the of the dashboard
![image](https://user-images.githubusercontent.com/50234893/57369925-21a16c80-718f-11e9-90ec-687b8543bcf7.png)

**Comment by JacobBirk** [comment]
@sashuk 
no data when using Chrome 
![image](https://user-images.githubusercontent.com/50234893/57370943-aee5c080-7191-11e9-854e-7af9e3315f9c.png)

**Comment by sashuk** [comment]
@JacobBirk Following was fixed:
- no title&save dialog in `Calypso dashboard`;
- controls for `Calypso dashboard` are now in the middle and are not overlapped with the right-side menu;
- when the plot is added via borehole modal, it is activated and put as the first one in the list;

Could you please check if the following is working now (the demo with recreating both issues is presented below)?
- the `9. 884` borehole particularly seems to be working in Chrome (Windows, MacOS);
- the translation texts seem to appear correctly (launched the page with `da_DK` locale);

![demo1](https://user-images.githubusercontent.com/1390758/57672636-763f5e80-764b-11e9-8f27-c1902fe78f6e.gif)

**Comment by JacobBirk** [comment]
@sashuk 
Looks fine.
The legend should include name - eg. 9.884

**Comment by sashuk** [comment]
@JacobBirk Could you please specify what legend should contain it? The one that is located in the right side of the Modal when the single measurement is clicked on the map?

**Comment by JacobBirk** [comment]
@sashuk The legend in the bottom of the timeseries 
DGU 9.884 - Waterlevel (meter)
instead of
Water level (meter), opdated ....

**Comment by sashuk** [comment]
@JacobBirk Got it, sure!

By the way, could you please check if the following is working now?
- the `9. 884` borehole particularly seems to be working in Chrome (Windows, MacOS);
- the translation texts seem to appear correctly (launched the page with `da_DK` locale);

**Comment by JacobBirk** [comment]
@sashuk check where? test version?

**Comment by sashuk** [comment]
@JacobBirk Yes, do you have a test deployment? I am just wondering where you have observed these bugs and if it possible to recreate them.

**Comment by JacobBirk** [comment]
@sashuk yes https://test.watsonc.gc2.io/app/jupiter/chemicals,sensor/#geodk.bright/9/10.07/56.8495/sensor.sensordata_without_correction,chemicals.boreholes_time_series_without_chemicals

updated by Martin earlier today

here the datamenu is empty

![image](https://user-images.githubusercontent.com/50234893/57715951-29be4800-7678-11e9-8cb0-cc2eb1518a08.png)

**Comment by JacobBirk** [comment]
@sashuk 
I might be a good idea if you could maintain the test site/keep til the test site updated.

I have data in menu after clearing site data.

![image](https://user-images.githubusercontent.com/50234893/57751295-8015a000-76e5-11e9-8daa-f6122686f62f.png)

**Comment by sashuk** [comment]
@JacobBirk Thank you for the details!

Sure, I've created the same issue recently https://github.com/sashuk/watsonc/issues/40 - also I think it will be really good to have some regression tests running on every code update (the mechanism already used for Vidi in general).

**Comment by sashuk** [comment]
@JacobBirk I've tested the link you've provided as well, so probably the issue was that the cache was not updated. Changes in legend were implemented in https://github.com/sashuk/watsonc/commit/68220b81de296f28ab7e21ea558fff4e4d3f76ba.

![plot](https://user-images.githubusercontent.com/1390758/57754492-2763f880-7721-11e9-95a6-5bf2fe81f146.png)
