### ISSUE TITLE
Vector layer is not loaded when starting below zoom level 15 using "Boreholes time series with chemicals"

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#39]
Start zoomed out with "Boreholes time series with chemicals"
![image](https://user-images.githubusercontent.com/3850918/57607188-c85c8300-756a-11e9-8da6-05c7a3abecfa.png)

Zoom in and vector will never load:
![image](https://user-images.githubusercontent.com/3850918/57607208-d9a58f80-756a-11e9-8425-179cd839d5d8.png)

It works alright with "Sensor data with correction". It seems Vidi tries to load the data from the very beginning, but with "Boreholes time series with chemicals" the request is canceled and never send again.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/5e0c7d104311afa971543d4e6fb86d364794c74e

![demo](https://user-images.githubusercontent.com/1390758/57640535-57a67c80-75e5-11e9-9351-ed6dcbf166ff.gif)
