### ISSUE TITLE
Handling of non existing chemicals on sensor.sensordata_with_correction

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#41]
When selecting both layers and an chemical which doesn't exist in `sensor.sensordata_with_correction`:
![image](https://user-images.githubusercontent.com/3850918/57683132-5f8d0d80-7633-11e9-842e-18d8fb607454.png)
You'll get an unhandled exception:
![image](https://user-images.githubusercontent.com/3850918/57683448-f35ed980-7633-11e9-96bf-5b14422b3fd7.png)
And `sensor.sensordata_with_correction` gets blue circles:
![image](https://user-images.githubusercontent.com/3850918/57683509-1e492d80-7634-11e9-81ca-7060410f5e60.png)
This situation needs to be handled both ways (`sensordata_with_correction` will get chemicals, which doesn't exist in `chemicals.boreholes_time_series_with_chemicals`)
The blue circles should be replaced with the default grey circle symbols.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/d1942739c58543ec53e10e8a59c3576cc17e667c

![checks](https://user-images.githubusercontent.com/1390758/57685343-42276600-766a-11e9-8fd0-314c986092e6.gif)
