### ISSUE TITLE
Map symbols in Calypso

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#42]
@sashuk @mapcentia 
We have rethought how we would like the symbols shown on the map.
The Startup menu 
![image](https://user-images.githubusercontent.com/50234893/58421233-bd880f00-808f-11e9-8aa3-97ce185143a9.png)
should be re-organised with headlines "grundvand", "Vandløb" and "nedbør"
- The layer "Jupiter boringer" refer to waterlevel and chemistry data from jupiter  (Cirkel (Circle))
- The layer "CALYPSO stationer" in "Grundvand" refer to sensor data with "Sensor.location.loctypeid=1" in watsonc DB (Cirkel (Circle))
- The layer "CALYPSO stationer" in "Vandløb" refer to sensor data with "Sensor.location.loctypeid=3" in watsonc DB (Diamant (diamond)
- The layer "CALYPSO stationer" in "Nedbør" refer to sensor data with "Sensor.location.loctypeid=4" in watsonc DB (Regndråbe (Raindrops))

Later on we will have a layer "Jupiter Anlæg!" (Trekant (triangle)

The file 
[Symbols.zip](https://github.com/sashuk/watsonc/files/3223856/Symbols.zip)
Contains the symbols used in the map

Meaning of colors
Orange #eb601d = Station belongs to WatsonC (All stations from Sensor.location)
Blue #1380c4 = Station belongs to other than WatsonC (Jupiter, m.m.)
Light blue #77cbe7 = Indicates stations with Water Level data, when this type of data is chosen. (Data from "Jupiter: Waterlevel"  and "sensor.station.stationtype = 1")
Light grey #eaeaea = If half of the symbol is light grey, it indicates that chemicals/water level only have been measured once at the specific station. (as now)
Dark grey #707070 = No data on the station for chosen datatype. (as now)
Green #009688, Yellow #f7a84d, Red #fc3c3c = Indicates stations with chemical data.
Left side of the symbol shows historical high for the station. Right side shows latest measurement. (as now)

Stroke
Black stroke = marks the currently selected station (in timeseries and profiles)
No stroke = everything not selected

WiFi-symbol
Blue WiFi = station is online (Rows from sensor.sensorhistorik where sensor.sensorhistorik.enddate = ‘2099-01-01’. If a stations is on the selected list the station is online, otherwise offine ==> Grey WiFi 

Graphical overview

![image](https://user-images.githubusercontent.com/50234893/58422654-6a17c000-8093-11e9-8d06-00c4de05238d.png)

**Comment by JacobBirk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Map symbols in Calypso](https://trello.com/c/FwKSi3OW/83-map-symbols-in-calypso)

**Comment by sashuk** [comment]
@JacobBirk Could you please confirm that there are still the same layers to load data from, however, the `sensordata` layer is now filtered in three different ways (depending on station type)?

**Comment by JacobBirk** [comment]
@sashuk exactly.
Later on we will have more river data (vandløb) to load, but these data are not ready jet

**Comment by sashuk** [comment]
@JacobBirk Thank you for the information!

**Comment by sashuk** [comment]
@JacobBirk Could you please specify what should be shown when every of `CALYPSO stationer` layers is shown? Should it be `water level` for every one of three layers (assuming that all of `CALYPSO stationer` with water sources)?

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Also could you please provide the location of the `sensor.station.stationtype` field (so it can be filtered)? Currently the `sensor.sensordata_with_correction` layer has the following fields:

```
[
        {
            "name": "gid",
            "type": "integer"
        },
        {
            "name": "the_geom",
            "type": "geometry"
        },
        {
            "name": "numofintakes",
            "type": "integer"
        },
        {
            "name": "boreholeno",
            "type": "integer"
        },
        {
            "name": "stationname",
            "type": "integer"
        },
        {
            "name": "watlevmsl",
            "type": "jsonb"
        }
]
```

**Comment by JacobBirk** [comment]
@sashuk 
Q1: For "grundvand" and "Vandløb" the datatype "water level" should be displayed. For "Nedbør" the datatype "nedbør" should be displayed.

Ole will help with pointing out the correct tables (if this is not given)

Later on more datatype might linked to the layers.

Q2: Ole will answer

**Comment by olemunch** [comment]
@sashuk 
Hi Alexsandr

Now sensor.sensordata_with_correction also contain "loctypeid" 
1: (Grundvand/groundwater), 
3 (Vandløb / rivers), 
4 (Nedbør/precipitation))

sensor.station.stationtype is now also added to sensor.sensordata_with_correction but since more than one  stationtype can be related to a location is added as a json object containing af list with one or more elements.

If eg. two waterlevel timeseries i present in sensor.sensordata_with_correction.watlevmsl and in case we also messured nitrate at the same location we would have 3 stations at the same location. So sensor.station.stationtype will be {1,1,3}
1: waterlevel (Vandstand)
2: flow (Vandføring) - does not exist now
3: chemistry - does not exist now
4: precipitation (Nedbør)

The column " watlevmsl" only contain water level data (vandstand). The json object has the same format as all json objects from jupiter boreholes.

We added a new column "precipitation" to sensor.sensordata_with_correction. This is a test where we generated a complete plotly graph content an graphs should be generated somewhat simlilar to profiles. We will create a new issue on how to deal with this! At the moment we should only show data from the "watlevmsl" column

I'm not sure that this is easily understood. Please ask again if its unclear.

**Comment by sashuk** [comment]
@JacobBirk @olemunch Thank you very much for the explanation! Now I do observe the `stationtype` in `feature[N].properties.watlevmsl` object.

> sensor.station.stationtype is now also added [...] as a json object containing af list with one or more elements.

Could you please specify if the `stationtype` is an empty array (not containing one or more objects), should all measurements be considered as **1** (waterlevel)?

Also seems like the `loctypeid` is still missing from the server response, could you please check (the cache hit shows `false`)?

![watsonc](https://user-images.githubusercontent.com/1390758/59210995-629efd80-8be1-11e9-8954-be9c8fb09fed.PNG)

**Comment by sashuk** [comment]
@JacobBirk @olemunch 

1. Could you please specify if regular blue and purple circles should be completely replaced by the new symbol notation?

![symbols](https://user-images.githubusercontent.com/1390758/59244958-36b76280-8c49-11e9-8da4-821bd3e6b88e.PNG)


2. Is the `boreholes_time_series_with_chemicals` same as `Jupiter boringer` and is the `sensordata_with_correction` same as `CALYPSO stationer`?

3. Will `sensor.sensorhistorik.enddate` be added to the station data?

**Comment by olemunch** [comment]
Hi again Alexandr @sashuk 
1) Yes blue and purple circles should be completely replaced
2) Yes, yes
3) We can add a tag indicating if the station is still active. Would you like it placed inside the JSON structure that contains data?

Comment to previous question:
I added loctypeid and stationtypeid in separate columns in the table sensor.sensordata_with_correction like this, because i thought it might be faster for you to search outside the JSON that contains all the data. But I can add both inside the JSON-object instead
![image](https://user-images.githubusercontent.com/51031638/59248684-66ec0a80-8c23-11e9-84c1-99077650985e.png)

**Comment by sashuk** [comment]
@olemunch Thank you very much! The station status can be placed as a table column, I think (just like `loctypeid` or `stationtypeid`).

> I added loctypeid and stationtypeid in separate columns in the table sensor.sensordata_with_correction like this, because i thought it might be faster for you to search outside the JSON that contains all the data. But I can add both inside the JSON-object instead

Thank you, but I think that it will be easier to keep them as regular columns.

**Comment by olemunch** [comment]
@sashuk 
A "status" column is added. 
0: never been online - no symbols added (0 stations at the moment)
1: previously online, but inactive (ikke online nu)
2: online data within last 24 hours (online)

stationtypeid is added both in separate column and inside JSON-structure in watlevmsl.

**Comment by sashuk** [comment]
@olemunch Thank you!

Current progress (default symbols were added):

![symbols](https://user-images.githubusercontent.com/1390758/59266529-66cb2980-8c7a-11e9-8670-7b3249d3566d.gif)

**Comment by olemunch** [comment]
Hi Alexandr @sashuk 
NICE!

A few corrections:
All jupiter boreholes should be shown as "status" = 0 (no symbol indicating online data)
eg 29. 36, 29. 33

In your screenshot 29. 398 is both present as a borehole in jupiter ( but without data) and as a sensor station in CALYPSO with online data (status = 2, dark blue signal symbols) Blue signal symbol should therefore be visible in this case

**Comment by mapcentia** [comment]
@sashuk @olemunch columns "status", "precipitation", "loctypeid" and "stationtypeid" are now added to the foreign table "sensor.sensordata_with_correction".

**Comment by olemunch** [comment]
@mapcentia 
Ok Martin - so altering the original table does not affect the foreign table automatically?
Thanks Martin

**Comment by sashuk** [comment]
@mapcentia @olemunch @JacobBirk Now the data is returned with additional properties `precipitation, loctypeid, stationtypeid, status`, so moving to further map symbols implementation.

**Comment by sashuk** [comment]
Taking into account online status:

![online](https://user-images.githubusercontent.com/1390758/59505506-2ff24f00-8ed8-11e9-8fe1-0ed09ccb7c23.gif)

**Comment by sashuk** [comment]
> Hi Alexandr @sashuk
> NICE!
> 
> A few corrections:
> All jupiter boreholes should be shown as "status" = 0 (no symbol indicating online data)
> eg 29. 36, 29. 33
> 
> In your screenshot 29. 398 is both present as a borehole in jupiter ( but without data) and as a sensor station in CALYPSO with online data (status = 2, dark blue signal symbols) Blue signal symbol should therefore be visible in this case

The problem with `sensor` features showing into the `boreholes` layer is processed in https://github.com/sashuk/watsonc/issues/43

**Comment by sashuk** [comment]
@mapcentia @JacobBirk @olemunch The feature was implemented in https://github.com/sashuk/watsonc/commit/a3363c6c4a4949388470558c88e90204fd451ff5

Every symbol has two parts: the actual symbol shape and the WiFi symbol.
The actual symbol representation is defined according to parameters `stationtype` (shape), `highlighted` (the border settings), `leftPartColor` and `rightPartColor` (in case if they are generated according to the chemical data).
The WiFi symbol representation is defined according to parameters `online` and `highlighted` (the border settings).

Please note that the problem with sensor features showing into the boreholes layer is processed in #43 .

Demo:

![symbols](https://user-images.githubusercontent.com/1390758/59597840-578e2500-912d-11e9-9849-c06c53407339.gif)
