### ISSUE TITLE
Intake number added to data object

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#45]
Now intake number is just the key a measurement has in the array. But intake number is a real id, which may differ from the place in the array. So now the dataobject has a `intakes` property:
![image](https://user-images.githubusercontent.com/3850918/59355061-a18a9b80-8d26-11e9-915c-00d2c5546a88.png)
The length of the `intakes` array corresponds with the length of `measurements`  and `timeOfMeasurement` and should be uses wherever intake number is displayed.

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/7eeccb7579ad36a72d6fc8306da4dfbff64b44a0

Demo:
![intake_numbers](https://user-images.githubusercontent.com/1390758/59661664-db074f00-91dd-11e9-8c80-d27959d9d70c.gif)
