### ISSUE TITLE
The Drag and Drop boxes now aligns to bottom of dialog

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#46]
![image](https://user-images.githubusercontent.com/3850918/59410283-c0397280-8db8-11e9-9078-f303fc222f40.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/dc5db5620359bb8e85b5e1c451956d6b9358f48d

![watsonc3](https://user-images.githubusercontent.com/1390758/59418185-2f37bb00-8dfb-11e9-9946-90a1e2ed302c.gif)
