### ISSUE TITLE
selection of Datasource and -types

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#47]

**Comment by JacobBirk** [comment]
@sashuk 
Datasource and datatypes are initially given in the welcome screen.
Afterwards Datasource and datatypes may be changed from the right menu 
![image](https://user-images.githubusercontent.com/50234893/59924154-62023480-9435-11e9-8c52-6c07f8b5c625.png)
The total list of datasource is listed in the right menu 
![image](https://user-images.githubusercontent.com/50234893/59924335-d1782400-9435-11e9-9a04-c740878d15aa.png)

and datatype is selected from a popup window 

![image](https://user-images.githubusercontent.com/50234893/59924460-0e441b00-9436-11e9-88ca-c28da93fc320.png)

With title "Vælg datatype"

The "vælg data" entry link should be removed
![image](https://user-images.githubusercontent.com/50234893/59924672-8ad6f980-9436-11e9-8d96-1d43fc882225.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Feature was implemented in the https://github.com/sashuk/watsonc/commit/fa38a01366e55884bfafcaa801aa24615335514b (with major refactoring and integration of [redux](https://redux.js.org/))

Demo:
![selector](https://user-images.githubusercontent.com/1390758/60321849-85d2f680-99b0-11e9-916a-05ce75287554.gif)

**Comment by JacobBirk** [comment]
Perfect

Jacob
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: Friday, June 28, 2019 8:26:18 AM
Til: sashuk/watsonc
Cc: Jacob Birk Jensen; Mention
Emne: Re: [sashuk/watsonc] selection of Datasource and -types (#47)


@mapcentia<https://github.com/mapcentia> @JacobBirk<https://github.com/JacobBirk> Feature was implemented in the fa38a01<https://github.com/sashuk/watsonc/commit/fa38a01366e55884bfafcaa801aa24615335514b> (with major refactoring and integration of redux<https://redux.js.org/>)

Demo:
[selector]<https://user-images.githubusercontent.com/1390758/60321849-85d2f680-99b0-11e9-916a-05ce75287554.gif>
