### ISSUE TITLE
Dashboard layout

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#48]
The up and down arrow may be hidden by the data window
Is it possible to add an option where a click in the top frame (marked with read) will push the dashboard up - 1. click > half size, 2. click > full size, 3. click > half size, 4. click > close
![image](https://user-images.githubusercontent.com/50234893/59925287-0eddb100-9438-11e9-97f1-8cb52bc2bcde.png)

Height of timeserie or profil should be adjusted to fit half size dashboard
to save space content in red box may be moved up
![image](https://user-images.githubusercontent.com/50234893/59925770-1b163e00-9439-11e9-8d9e-34e86a8ccc8d.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Implemented in https://github.com/sashuk/watsonc/commit/c747d2fe7da269752136ed6fb5ca4dec5eb6538d

Demo:
![dashboard_1](https://user-images.githubusercontent.com/1390758/60175780-1ab9e080-9847-11e9-9932-dbfa30390de2.gif)

**Comment by JacobBirk** [comment]
Great

Jacob
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: Wednesday, June 26, 2019 1:19:56 PM
Til: sashuk/watsonc
Cc: Jacob Birk Jensen; Mention
Emne: Re: [sashuk/watsonc] Dashboard layout (#48)


@mapcentia<https://github.com/mapcentia> @JacobBirk<https://github.com/JacobBirk> Implemented in c747d2f<https://github.com/sashuk/watsonc/commit/c747d2fe7da269752136ed6fb5ca4dec5eb6538d>

Demo:
[dashboard_1]<https://user-images.githubusercontent.com/1390758/60175780-1ab9e080-9847-11e9-9932-dbfa30390de2.gif>
