### ISSUE TITLE
Timeserie plot

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#49]
add a download buttom 
![image](https://user-images.githubusercontent.com/50234893/59926798-56197100-943b-11e9-9259-4369141613aa.png)
with an option to pack data in an excel file - one tab per dataserie (is that possible?)

Add y-axis on plot
Resize plot height according to #48

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Implemented in https://github.com/sashuk/watsonc/commit/634f1d8305341888ce226c07a208cad987ee7d02

Creating and downloading plot's XSLX:
![downloading](https://user-images.githubusercontent.com/1390758/60187413-21088680-9860-11e9-8d04-358cd03e7180.gif)

Viewing the XSLX:
![excel](https://user-images.githubusercontent.com/1390758/60187395-18b04b80-9860-11e9-815d-dd11a7cafa47.gif)

**Comment by JacobBirk** [comment]
Looks good👍

Jacob
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: Wednesday, June 26, 2019 4:18:02 PM
Til: sashuk/watsonc
Cc: Jacob Birk Jensen; Mention
Emne: Re: [sashuk/watsonc] Timeserie plot (#49)


Closed #49<https://github.com/sashuk/watsonc/issues/49>.
