### ISSUE TITLE
Adjustments on design

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#5]
1. Move breadcrumb to top-bar, so it always visible
2. Move top-bar buttons to round buttons over map.
![image](https://user-images.githubusercontent.com/3850918/49501863-25456600-f874-11e8-808d-90a02503b842.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify if secondary map controls should still be left, as the previous design guide suggested leaving only zoom controls (and Time series / Projects buttons)?

![controls](https://user-images.githubusercontent.com/1390758/49562284-cf48ef00-f955-11e8-8b77-d574e184109a.png)

**Comment by mapcentia** [comment]
@sashuk secondary map controls should still be there. I added some back yesterday bb0ec407a61ba3a7654a85b3d3ff087fa4f5c0b6

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Style changes were applied in https://github.com/sashuk/watsonc/commit/99c5f74648b7761908e0a91b600622c567b69e3f

![design](https://user-images.githubusercontent.com/1390758/49563533-3cab4e80-f95b-11e8-8126-dd954568cf38.png)
