### ISSUE TITLE
Bug - right menu data source and -type 

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#52]
@sashuk Content in "datakilder og -typer" (replace s with r in types) should open in the wide panel as projekter, tidsserier and profiler
![image](https://user-images.githubusercontent.com/50234893/60675715-45c2b680-9e7d-11e9-9113-abd4f90b33ba.png)

**Comment by sashuk** [comment]
@JacobBirk Fixed in https://github.com/sashuk/watsonc/commit/7d94f437b486178501f85cd958097be289791b80

Demo:

![selector_1](https://user-images.githubusercontent.com/1390758/60696930-6725b000-9f1a-11e9-8f98-676c391b823b.gif)

**Comment by sashuk** [comment]
@JacobBirk The translation was fixed in https://github.com/sashuk/vidi/commit/05df36a7aa31613d0e8a72cc99d2d131837c8376
