### ISSUE TITLE
Bug/adjustment - coloring of symbols

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#53]
There is an detection limit related to all datapoints for chemical in the Jupiterdatabase. If chemical isen't detected  pcjupiterxlplus.GRWCHEMANALYSIS.attribute would include '<'.

The attribute is added to the JSON structure. I think Martin will do this. 
All datapoints with '<' is neglected in analysis of "max of historical data" (max) and "latest" (Senest)

![image](https://user-images.githubusercontent.com/50234893/60804819-b1a76680-a17e-11e9-899c-6051c28fe71c.png)

If the given chemical isen't detect the text should be "i.p." ("n.d." in english) and the colored is green.

In the data window below you will see there intakes and the colors of each should reflect the data related to the seperate intake
![image](https://user-images.githubusercontent.com/50234893/60804274-6ccf0000-a17d-11e9-91e3-9d6607dd52ba.png)

Nitrat (1) is green/green
Nitrat (2) is orange/orange 
Nitrat (3) is red/red

The "not detected" data points is marked on the graph with red marks and hover test as in https://trello-attachments.s3.amazonaws.com/5baf38c8e64a5564ed88bf00/5cb70b038e8be47ccf1ad5c0/a3ec64bdc62fd6f8ff8fa98014ea5d4d/Layout_CALYPSO_kemi_detectlimit.html

**Comment by sashuk** [comment]
Intakes for every chemical are now colored differently (implemented in https://github.com/sashuk/watsonc/commit/6aa033dc4de778b9f2741f62a647bfa60d6b9d5c)

![intakes](https://user-images.githubusercontent.com/1390758/60897409-9e89b900-a29a-11e9-9593-0e70df65aa62.PNG)

**Comment by mapcentia** [comment]
@sashuk Objects now have a `attributes` property. Objects from sensor schema doesn't have this property, so a check in the code has to be done:
```json
{
  "unit": "µg/l",
  "title": "Atrazin, desisopropy",
  "intakes": [
    300
  ],
  "attributes": [
    [
      "<"
    ]
  ],
  "boreholeno": "100.  102",
  "measurements": [
    [
      0.01
    ]
  ],
  "timeOfMeasurement": [
    [
      "1998-02-23T10:40:00"
    ]
  ]
}
```

**Comment by sashuk** [comment]
@mapcentia Got it, thank you!

**Comment by sashuk** [comment]
@JacobBirk Could you please specify if `If the given chemical isn't detected` means that **all** of data points have a corresponding `<` attribute, so there are no points to detect latest or max values?

**Comment by JacobBirk** [comment]
If latest isn't detected a "i.p." is added to the mouse over: Senest: i.p.

if no points at all is detected "i.p." is added to the mouse over: max: i.p.

**Comment by sashuk** [comment]
@JacobBirk Got it, thanks!

**Comment by JacobBirk** [comment]
By the way: 

In wells with 2 or more intakes the coloring should be determine as:
![image](https://user-images.githubusercontent.com/50234893/61374855-bc0fe180-a89d-11e9-8cf7-542aef1735ea.png)

Left: max of historical values for intake 1, 2, etc.
Right: max of latest value for intake 1, 2, etc.

Current example: left: red (60), right: red (52)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Measurements that have corresponding `<` attribute, are marked with red, the `i.p.` text and new coloring scheme were also applied in https://github.com/sashuk/watsonc/commit/9fd8f388e2a76304c51e50c34e7bb8c74ec228d7

Demo:

![plot](https://user-images.githubusercontent.com/1390758/61424176-42cbc980-a945-11e9-9118-bac8252d72af.gif)

**Comment by JacobBirk** [comment]
Very nice:-)
