### ISSUE TITLE
Right menu open at startup

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#55]
At startup the right menu should be "half open" as
![image](https://user-images.githubusercontent.com/50234893/61375731-e6629e80-a89f-11e9-85d8-e1ca2f83f597.png)
When the right menu is full size and closed it return to half open

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Right menu is opened at startup (implemented in https://github.com/sashuk/watsonc/commit/b088f53f864030d6168ddb5115450738ceced7e3)
