### ISSUE TITLE
BUG: no data is loaded in my browser 

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#57]
Often I don't get data loaded and I have to "clear site data" and reload the application
![image](https://user-images.githubusercontent.com/50234893/61376593-c3d18500-a8a1-11e9-918a-2858d5f3f3a2.png)

**Comment by sashuk** [comment]
@JacobBirk Could you please specify the following:
- when does this happen (on initial load after cache reset, after a page refresh, after some time interacting with the page)?

**Comment by JacobBirk** [comment]
After cache reset and page refresh everything is fine.
I only observe the problem when starting the application. It never appears during a session (or I haven't observed it)

**Comment by sashuk** [comment]
@JacobBirk Thank you for the information! Could you please also specify if this happens when you are consequently clicking various boreholes without any other interactions? Could you please make a screenshot of the `Console` view in Chrome DevTools in case you will have it open?

**Comment by JacobBirk** [comment]
I've clicked on 20-30 boreholes and there is no changes in memory usage or response speed
![image](https://user-images.githubusercontent.com/50234893/61574240-06bb7480-aabd-11e9-85e8-6d74d834b800.png).

After making timeseries and releading the applikation the error occurs again 
![image](https://user-images.githubusercontent.com/50234893/61574358-da085c80-aabe-11e9-9f9b-eb0182e4a33d.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Thanks you very much for the detailed description! Fixed in https://github.com/sashuk/watsonc/commit/ed1ef770eae95a9d9cb3c85b2db65f6a109a3d8e
