### ISSUE TITLE
Display order of menus

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#58]
Is it possible to control the display order of the different menus? E.g. if I click on the dash board if will appear in front of the data menu and the right menu and if I click on the data menu it will appear on top of the dashboard menu.

Or is it possible to close the data menu at reduce the right menu to half size when clicking on the dashboard? (second priority)

![image](https://user-images.githubusercontent.com/50234893/61377057-c08ac900-a8a2-11e9-96da-06d487b9e89c.png)

**Comment by sashuk** [comment]
@JacobBirk There are three levels now - the Dashboard, Borehole modal or Main menu take the leading role depending on the last clicked item, implemented in https://github.com/sashuk/watsonc/commit/79e33852d84ce7ad90792c320062b86295c59641.

Demo:

![windows](https://user-images.githubusercontent.com/1390758/61430423-69492f00-a95c-11e9-902d-ac2989e6e555.gif)

**Comment by JacobBirk** [comment]
Very nice:-)
