### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#59]
I would like the high of the timeserie to be adjusted to the height of the dash board
Half size dash board = height of one timeseries or profile
full size dash board = = height of two timeseries or profile
![image](https://user-images.githubusercontent.com/50234893/61377911-6ee33e00-a8a4-11e9-8871-bf7ebeadf846.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Implemented in https://github.com/sashuk/watsonc/commit/0c14dbe4404c513801dba9cf323c139db914aa5d

Demo:
![dynamic_height](https://user-images.githubusercontent.com/1390758/61631360-bca0e180-acbc-11e9-873c-f33407b78e76.gif)
