### ISSUE TITLE
Water level should have its own category

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#6]
Water level should have its own category called `Vandstand`
![image](https://user-images.githubusercontent.com/3850918/49504904-eebf1980-f87a-11e8-91f4-dc4189319e17.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/eae9400c659e02f02d011d6a5213f116f2559f66

![intakes](https://user-images.githubusercontent.com/1390758/49531771-fbcd1e80-f8f5-11e8-956e-6a756cb9a926.png)
