### ISSUE TITLE
intake in legends

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#60]
Please add the intake no to the legend. As: _DGU 34.1695(1) - Nitrat......_
![image](https://user-images.githubusercontent.com/50234893/61378241-41e35b00-a8a5-11e9-9690-b1e4def79edf.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Legend now shows the intake number (according to the `intakes` property), implemented in https://github.com/sashuk/watsonc/commit/9fd8f388e2a76304c51e50c34e7bb8c74ec228d7

Demo:
![intake](https://user-images.githubusercontent.com/1390758/61424124-013b1e80-a945-11e9-922f-2d9fb1af2d00.PNG)
