### ISSUE TITLE
Marking selected intems with black outline

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#61]
Wells and stations added to a timeserie or profile is marked with black outline (as shown in "markeret". 
![image](https://user-images.githubusercontent.com/50234893/61433915-dba61900-a934-11e9-9e36-933a64ad44e2.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Dynamic highlighting was implemented in https://github.com/sashuk/watsonc/commit/8330529c25bcf62a2569da6ab64553640dfc9255

Demo:
![highlighting](https://user-images.githubusercontent.com/1390758/61515316-ea73f500-aa34-11e9-9c00-dc77a5073c12.gif)
