### ISSUE TITLE
calypso stations are always blue

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#63]
Calypso stations should always be blue - only the wi-fi symbol change color (blue online, gray offline) 
![image](https://user-images.githubusercontent.com/50234893/61434503-73f0cd80-a936-11e9-8c11-abd9acc41999.png)
If Calypso stations are placed at same location as a Jupiter well the Jupiter color should overrule the color of the calypso station

**Comment by sashuk** [comment]
@mapcentia @JacobBirk The ordering of layers was set, the Calypso features are now blue when the chemical is selected, implemented in https://github.com/sashuk/watsonc/commit/d5ddae946ac606fa47b7df58bcfe0bfcdbd71c47

Demo:
![ordering](https://user-images.githubusercontent.com/1390758/61516880-82271280-aa38-11e9-8a03-eb1ea85aa6d3.gif)
