### ISSUE TITLE
Mouseovers

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#64]
New mouseovers
![image](https://user-images.githubusercontent.com/50234893/61435235-53c20e00-a938-11e9-9313-83f368cf34a7.png)

**Comment by sashuk** [comment]
@JacobBirk Could you please specify if mouseovers should be regular HTML titles?

![title](https://user-images.githubusercontent.com/1390758/61671263-644bfd00-ad19-11e9-8e7f-2382e91d201d.png)

**Comment by JacobBirk** [comment]
Looks fine😉

Jacob
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: Tuesday, July 23, 2019 1:13:42 AM
Til: sashuk/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [sashuk/watsonc] Mouseovers (#64)


@JacobBirk<https://github.com/JacobBirk> Could you please specify if mouseovers should be as a regular HTML titles?

[title]<https://user-images.githubusercontent.com/1390758/61671263-644bfd00-ad19-11e9-8e7f-2382e91d201d.png>

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Titles and translations were added in https://github.com/sashuk/watsonc/commit/c99975490fea61fbfc3d6f831f1dd4e8bcb6f22f
