### ISSUE TITLE
Loading projects

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#65]
Loading an existing project should restore the dashboard with timeseries and profiles.

It is not possible for me to test the "open existing project" option because I'm not able to login at this stage
![image](https://user-images.githubusercontent.com/50234893/61574443-2ef8a280-aac0-11e9-8865-16f6855c72d1.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk The sign-in dialog can now be called from the `IntroModal` window (if the application is already authenticated, then the `IntroModal` shows both local and user's projects), implemented in https://github.com/sashuk/watsonc/commit/e8fa9a3299bc9018ad8d8d45a7ed5c4d288b2ce5

Demo:
![loading](https://user-images.githubusercontent.com/1390758/61686035-1bb03600-ad51-11e9-9289-014843dd166c.gif)
