### ISSUE TITLE
Custom designed graphs

### ISSUE THREAD

**Issue by olemunch** [sashuk/watsonc#69]
Hi @sashuk
In some cases we would like to create special graphs which are not just standard timeseries
At the moment all graph data has the form:
{"unit": "m DVR90", "title": "Vandstand", "intakes": [1.0], "boreholeno": "SofiendalEnge3", "measurements": [[0.0, 0.0, 0.0 etc...

We would like to add a possibility in some cases to replace this standard form with a more customized  form.  Therefore a test must be made within CALYPSO to se if data is "standard" or "custom". Can you suggest how to do this based on this example?
[Demo Precipitation.txt](https://github.com/sashuk/watsonc/files/3434634/Demo.Precipitation.txt)

We made an example where we want to plot a precipitation timeseries as a bar plot. We want the user to be able to show daily or weekly og monthly data. Therefore we generated 3 bar series from the same data. 

![image](https://user-images.githubusercontent.com/51031638/61928315-50ea9d00-af78-11e9-9845-cd12335c537d.png)

Each timeseries is a plotly Trace and contain all the information needed to plot it directly. But there is also a layout object from wich we need to add elements to the standard graph layout used in CALYPSO. We want these data to be shown on a secondary y-axis with a fixed range. 

ploting the "daily" precipitation must append following to the existing layout definition in CALYPSO:
"layout": {"yaxis2": {"range": [0, 100],"showgrid": "false", "overlaying":"y","side":"right"}}

Its important that we can generate graphs with both "standard" time series and "custom" elements. Adding a "standard" timeseries after adding the "custom" timeseries must there possible. 

If adding more than one custom graph result in conflicts in the layout properties the latest added custom graph must "overrule" the first one. 

We made a javascript graph to illustrate this example (attached as a txt file - rename to .html)

In the sensordata_with_correction table in the watsonc-database you can find the precipitation data in the "precipitation" column 

![image](https://user-images.githubusercontent.com/51031638/61933024-20f5c680-af85-11e9-8793-3583c18b3f2a.png)

![image](https://user-images.githubusercontent.com/51031638/61933264-c741cc00-af85-11e9-9706-cf3a4cc07946.png)

**Comment by sashuk** [comment]
@olemunch What if to implement this just as in the example that you have provided? Calypso is able to distinguish the regular or complex data format, so if the measurement has the non-empty `precipitation` value, then three additional graphs will be displayed, activated/deactivated via plot legend.

**Comment by olemunch** [comment]
Hi Alaxsandr
@sashuk 
I'm not sure what you're asking?
We might replace data in the watlevmsl column with the complex structure so I guess its not enough to check if it's non-empty. Also data in the precipitation column could follow the regular data format.

But if you can see a way through just make a test/demo

**Comment by sashuk** [comment]
@olemunch Alright, I will start on it and propose the solution along the way then!

**Comment by sashuk** [comment]
@olemunch @JacobBirk  Hello! There are a couple of questions:

1. Please consider the following image:

![data](https://user-images.githubusercontent.com/1390758/62017467-53076280-b1e9-11e9-8a46-3332c986f734.PNG)

The precipitation data has a red border, the water level has the blue border. Could you please specify if the precipitation custom graphs should go along with the water level data (the `Nedbør` in this case) or it should be a separate measurement that has its own drag-and-droppable control in the measurements list (the purple zone)?

2. Is it possible that, for example, the `watlevmsl`, could have a custom data format for some boreholes?

3. Should the user have the ability to enable or disable `daily / weekly / monthly` graphs like in the provided HTML example?

4. Do  `daily / weekly / monthly` graphs have multiple inputs just like the regular measurements?

5.  

> If adding more than one custom graph result in conflicts in the layout properties the latest added custom graph must "overrule" the first one.

Do you mean multiple `{daily: {}, weekly: {}, monthly: {}}` data sets or `daily`, `weekly` and `monthly` graphs separately? In case of conflicting `daily`, `weekly` and `monthly` graphs I think the solution is to have separate `y` axes (`yaxis2` for `daily`, `yaxis3` for `weekly` and `yaxis4` for `monthly`), actually it was already implemented in the demo below.

**Comment by sashuk** [comment]
@olemunch @JacobBirk The progress so far:

![customgraphs](https://user-images.githubusercontent.com/1390758/62020120-3b81a700-b1f4-11e9-8221-e55f2c658681.gif)

**Comment by WatsonC-hub** [comment]
@sashuk 
1) should be a separate measurement that has its own drag-and-droppable control in the measurements list - yes

2) Yes that is possible in the future. We could add a certain unique element to the json structure or you could perhaps just test if the structure contain a layout element to determine if its a "regular" or "custom" graph

3) yes, unless that gives some problems?

4) not sure I understand this question

5) yes diffent ranges could be handled by a new y-aksis for each, however that does not apply for any kind of "custom" graph. We might want to plot a custom graph on the y1 axis in the future. So I think we should always **use the specified axis**. We could then of course  choose to specify y2, y3, y4 in the data set if we think data will be plotted together. So still if there is any conflicting setting in the layout property then the latest added element must overrule the first.

**Comment by sashuk** [comment]
@WatsonC-hub Thanks!

1. Done
2. What if to make `precipitation` to have a regular data format, like other measurements?

For example, `watlevmsl` has the following structure:

```
{
    "title": "Nedbør"
    "key": "watlevmsl",
    "intakes" : [..],
    "measurements": [...],  // actual data
    "timeOfMeasurement": [...] // actual time data
    ...
}
```

The `precipitation` has the following format:
```
{
    "daily": {...},
    "weekly": {...},
    "monthly": {...}
}
```
What if to unify the data format? So, `precipitation` will look like this:

```
{
    "title": "Precipitation"
    "key": "precipitation",
    "intakes" : [..],
    "data": {
        "daily": {...},
        "weekly": {...},
        "monthly": {...}
    }
    ...
}
```

So, whenever the measurement will not have the "measurements" and "timeOfMeasurement" keys but will have the "data" key -will be considered the **custom** one.

3. Done
4. I was wondering if the `precipitation` can have data available for multiple borehole intakes? 
5. Should it be possible to display, for example, `daily` and `monthly` graphs together?

**Comment by WatsonC-hub** [comment]
2. Yes we can do that - good idea
4. Not relevant for precipitation, but yes for other future data - so datastructure proposed in (2) is a good idea.
5. Yes it should be possible. Its not relevant for precipitation though.

**Comment by sashuk** [comment]
@WatsonC-hub Great, thanks! Looking forward to the change in data format.

Concerning the conflicting y-axis issues - could you please specify what is wrong with the provided HTML example (the `.txt` file in the message above)?

**Comment by olemunch** [comment]
@sashuk now im signed in as olemunch again...

in the example this is the case
  yaxis2:{
    showgrid: false,
    overlaying:'y',
    side:'right',
	range:[0,100]
    }
But for the monthly precipitation we need range:[0,200] on the y2 axis
So if we first add daily precipitation an then monthly the range:[0,100] should be changed to range:[0,200] or whatever is defined in the Trace "monthly"

**Comment by sashuk** [comment]
@olemunch Got it, thanks! However, what if to detect the maximum range among all graphs (`daily`, `weekly` and `monthly`) and to use it? Or it is essential to have a maximum range value depending on enabled graphs (for example, when comparing `daily` and `weekly` probably there is no need in the bigger range that is used for the `monthly` graph).

**Comment by olemunch** [comment]
@sashuk 
Detecting max range is smart however for other settings we need to just overwrite. So you can make a special case for the range if its easily done

**Comment by sashuk** [comment]
@olemunch Got it, then the range will be set as the `[0, MAX_RANGE]`. However, when we are talking about other settings, does it mean that layout for custom graphs (with max range) should overwrite the layout for regular measurements as well?

**Comment by olemunch** [comment]
@sashuk 
I think it should rather be [MIN_RANGE, MAX_RANGE]

yes it will will in principle be possible to overwrite settings used by any Trace on the graph. But we will not introduce a fixed range[] on y-axis 1 so normal graphs should not be afftected.

**Comment by sashuk** [comment]
@olemunch Sure, the `[MIN_RANGE, MAX_RANGE]` was implemented in https://github.com/sashuk/watsonc/commit/83ce2764b88992742d86da1bf86c921e11d47fe5 along with the support for the custom graphs (the layout settings are only applied for custom graphs).

However, could you please specify if the `precipitation` will have unified with other chemicals data format soon?

**Comment by olemunch** [comment]
within a few hours I will get to it

**Comment by sashuk** [comment]
@olemunch Great, thanks!

**Comment by olemunch** [comment]
@sashuk
New data available in sensordata_with_correction - I adjusted it manually, hope there is no errors - let me know :-)
Only daily and monthly data is know in the example

**Comment by sashuk** [comment]
@olemunch Thank you very much! Seems correct, now measurements have the same data format and every measurement is checked for being **custom graph**.

@mapcentia @olemunch Implemented in https://github.com/sashuk/watsonc/commit/76145c29b5c9d59831abff744fcfc56d1e7b7680

Demo:
![grpahs](https://user-images.githubusercontent.com/1390758/62099611-3dfe0280-b2c1-11e9-917e-c307d2b363cb.gif)

**Comment by olemunch** [comment]
@sashuk
Hi, one correction

I did want 2 dragable objects insted of just "PRECIPITATION"
st_restrup1: daglignedbør
st_restrup1: månedlig nedbør 

From previous question 1:
it should be a separate measurement that has its own drag-and-droppable control in the measurements list - yes

**Comment by sashuk** [comment]
@olemunch Got it, reopening the issue (so, if `st_restrup1: daglignedbør` is added to the plot, the `st_restrup1: månedlig nedbør` will not be added automatically) in order to implement processing `daily/weekly/monthly` graphs separately.

**Comment by olemunch** [comment]
@sashuk 
a general graph issue:
-Why does the second y-axis not show on the graph? It should be resized to fit the frame
-the "showgrid": "false" parameter in the layout should make gridlines invisible for y-axis2

**Comment by sashuk** [comment]
@olemunch The general issues were fixed in https://github.com/sashuk/watsonc/commit/1045ae5390464cb180f12c1b18b820d6c68c17b6

Demo:
![legend](https://user-images.githubusercontent.com/1390758/62103863-588ba800-b2d0-11e9-85c5-b15a40557854.gif)

Getting to the splitting of `precipitation` measurement.

**Comment by olemunch** [comment]
@sashuk 
Wonder why the x-axis labels (Apr2019, May2019...) do not show up before you turn of the monthly graph?
Otherwise that looks GREAT!

**Comment by sashuk** [comment]
@olemunch Thank you very much for noticing! This is a known issue (actually the legend is positioned wrong after resize; after it is redrawn it is shown correctly): https://github.com/plotly/plotly.js/issues/1199, I will try to find the workaround for it.

**Comment by sashuk** [comment]
@olemunch Legend positioning was fixed in https://github.com/sashuk/watsonc/commit/5420d416b92d0f3845f81dd73ba69fdd98a15128

Demo:
![legend](https://user-images.githubusercontent.com/1390758/62113772-c5f70300-b2e7-11e9-9dfe-d2f57e929998.gif)

Resuming the splitting of custom graph measurements.

**Comment by sashuk** [comment]
@mapcentia @olemunch Splitting of custom graphs on separate measurements was implemented in https://github.com/sashuk/watsonc/commit/fa89bc701f44616a5619fa39bc6f076f929a5302

Demo:
![split](https://user-images.githubusercontent.com/1390758/62120201-b8e01100-b2f3-11e9-8142-e132facddae7.gif)
