### ISSUE TITLE
Only the first intake is listed in pop-up

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#7]
When selecting a borehole with multiple intakes only one intake can be plotted. In this one a ` Water level (#2)` is missing 
![image](https://user-images.githubusercontent.com/3850918/49514980-e7593980-f895-11e8-88f3-81fd1a35faff.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/eae9400c659e02f02d011d6a5213f116f2559f66

![intakes](https://user-images.githubusercontent.com/1390758/49531771-fbcd1e80-f8f5-11e8-956e-6a756cb9a926.png)
