### ISSUE TITLE
Boreholes coloring

### ISSUE THREAD

**Issue by sashuk** [sashuk/watsonc#70]
Please refer to https://github.com/sashuk/watsonc/issues/67#issuecomment-516267483

A possible fix is to replace the RGB color notation to the HEX one (https://github.com/sashuk/watsonc/issues/67#issuecomment-516263393)

**Comment by sashuk** [comment]
@olemunch Could you please specify if I should replace all the RGB colors with the HEX ones in the profile script?

**Comment by olemunch** [comment]
@sashuk 
yes if thats farly easily done and if we believe that will fix color issues
lets try it

**Comment by sashuk** [comment]
@olemunch Got it, thanks!

**Comment by sashuk** [comment]
@olemunch Could you please specify any example borehole and chemical where the wrong coloring can be observed?

**Comment by olemunch** [comment]
I dont think i can create a graph where the colors are wrong. It seems to work out fine when I run the script. But in these examples they seem wrong (not 100% sure)

https://user-images.githubusercontent.com/1390758/61948724-34cc1780-afdb-11e9-879f-01ff43e2ec00.gif

https://user-images.githubusercontent.com/1390758/61950360-2d5b3d00-afe0-11e9-89b0-d6ad6db9f207.gif

https://user-images.githubusercontent.com/1390758/62035053-aa292980-b221-11e9-98c0-e2fbc96287ac.PNG

Colors of boreholes come from "RockSymbol_color_code.csv"

Could the opacity be a part of the problem (rgba insted of rgb...??)
Could you make a test to see if rgb(xxx,xxx,xxx) or if HEX codes changes anything?

symbol	tekst	rgba
dk	campanien-maastrichtien kalksten	rgba(128, 255, 153,1)
sk	campanien-maastrichtien skrivekridt	rgba(128, 255, 153,1)
...
...

**Comment by sashuk** [comment]
@olemunch 

**Experiment:** the following was performed (analyzing single borehole):

1. Generate the profile with the regular `RockSymbol_color_code.csv` - the specific borehole has the `campanien-maastrichtien skrivekridt`, which has the `rgb(128, 255, 153)` color. The built profile is the upper one in the demo below;

2. Replace the `rgb(128, 255, 153)` with the equivalent HEX value `#80ff99` in the `CSV` file and build the profile with the same chemical element **and** other parameters. The built profile is the lower one in the demo below;

**Results:**

1. The HEX notation indeed affects the coloring of all the elements and the coloring is correct when the HEX notation is used;

2. Using `RGB` or `RGBA` notation does not affect the coloring - it is invalid in both cases.

**Steps to fix the problem:** replace all the `RGBA` notations to `HEX`, but it is still not the reason, I think.

The experiment visualization:

![coloring](https://user-images.githubusercontent.com/1390758/62347392-22e2fb00-b52c-11e9-972b-e3f19f821ec6.gif)

---

The Python script passes the data to the frontend correctly (the AJAX response part for the analyzed  borehole), colors are passed correctly, so seems like Plotly is not correctly processing the color directive by itself:

![bar](https://user-images.githubusercontent.com/1390758/62348380-52473700-b52f-11e9-8999-9a15174340d3.PNG)

**Comment by olemunch** [comment]
@sashuk 
Well if HEX code solves the problem let's change everything. Will you change in the .CSV file or will you convert to hex inside the script?

There is a small issue with the text label where '(' is displayed as %28 and ')' is displayed as %29. why?

**Comment by sashuk** [comment]
@olemunch Sure, I will check the `()` issues as well. I think the `rgb2hex()` will be more optimal, than replacing all the occurrences - going to commit it soon!

**Comment by olemunch** [comment]
@sashuk 
Great!

When do you think Martin will commit to the test version for us to try it out? Can you do that?

**Comment by sashuk** [comment]
@olemunch Seems like Plotly does not allow parentheses in the hover text (only specific HTML tags), is it okay to drop them?

![hover](https://user-images.githubusercontent.com/1390758/62352901-e4edd300-b53b-11e9-9c87-4c6ffbd20960.gif)

I think Martin will be back in a couple of days or next week. I will check if I have access to the server.

**Comment by olemunch** [comment]
@sashuk 
Yes, perfekt... 
but strange - here it's no problem

From Javascript...
"text": "-12.1(bund, kote)<br>ds, glacial smeltevandssand"

![image](https://user-images.githubusercontent.com/51031638/62353270-91af5c80-b50a-11e9-85c7-c1cc0a55a803.png)

**Comment by sashuk** [comment]
@olemunch Seems like this is the reason why colors are not working as well - something with the way parentheses are processed, investigating.

**Comment by olemunch** [comment]
@sashuk 
That makes sense! If you can figure out why that's perfekt. Otherwise it should be possible to avoid using parentheses

**Comment by sashuk** [comment]
@olemunch The problem was found, the JavaScript code was not processing data correctly. The coloring and splitting of every intake bar into `max`  and `latest` sub bars was added.

I've checked the access, now I can not access the watsonc.mapcentia.com with credentials that I have. However, you can check the latest version via [:link: development Calypso version](https://vidi.alexshumilov.ru/app/jupiter/chemicals,sensor/#stamenTonerLite/15/9.8484/57.0034/v:chemicals.boreholes_time_series_with_chemicals,sensor.sensordata_without_correction,chemicals.boreholes_time_series_without_chemicals).

Demo:

![colors2](https://user-images.githubusercontent.com/1390758/62359335-2cc72700-b549-11e9-98c3-34027933a07a.gif)
