### ISSUE TITLE
Labels and legend text

### ISSUE THREAD

**Issue by olemunch** [sashuk/watsonc#71]
@sashuk @mapcentia 
testing https://watsonc.vidi.gc2.io/app/jupiter/chemicals,sensor/#geodk.bright/7/9.4482/56.069/

1) Labels on sensordata when "mouse over": "DGU nr." should be removed. "Sønderbro3" is perfekt.
The text "Sønderbo3" comes from the "boreholeno" in the JSON-object. The same text should also be used in the data-menu insted of "302", also when the item is dragged to the graph- see screenshoot no2 and again in the graph legend, pic 3. The number 302 is not relevant at all for the users.

2) The text "Opdateret 7. aug" is not needed and should be removed to save space in the legend. Graphs are always updated (should be). (pic3)

3) In some cases the legend overlaps the x-axis title - see pic 3 left graph. When an item on the legend is clicked and the graph updates the problem is no longer there. Can we ensure that graphs update correctly when changing from matrix to row view? 

![image](https://user-images.githubusercontent.com/51031638/62649149-9a61c180-b954-11e9-86ac-1db2bff7277b.png)

 
![image](https://user-images.githubusercontent.com/51031638/62649750-adc15c80-b955-11e9-8400-263110147e58.png)

![image](https://user-images.githubusercontent.com/51031638/62650039-3fc96500-b956-11e9-8a34-252c1b116084.png)

**Comment by sashuk** [comment]
@olemunch @mapcentia  Could you please clarify concerning the **(1)**? The title of the measurement modal (pic. 2) is already taken from the actual `boreholeno` field, as you can see on the screenshot of the data, which has the value `302` - could you please check if the backend is actually sending the correct `boreholeno` field?

Data:
![test](https://user-images.githubusercontent.com/1390758/62859611-39f5ca00-bd30-11e9-82a0-0bce92a3fd6a.PNG)

**Comment by olemunch** [comment]
@sashuk 
Inside the watlevmsl there is also a "boreholeno" which I should have specified. We would like to use the text there instead.

In this example boreholeno = "Seges"

![image](https://user-images.githubusercontent.com/51031638/62862474-30576c80-bd06-11e9-942a-6a0a00340835.png)

**Comment by sashuk** [comment]
@olemunch Thank a lot!

**Comment by sashuk** [comment]
@mapcentia @olemunch Implemented in https://github.com/sashuk/watsonc/commit/c3054c926baf50991785bdfa3e2d9325205494b0

Demo:
![titles](https://user-images.githubusercontent.com/1390758/62865403-02434e00-bd41-11e9-8870-08b2802e00fd.gif)
