### ISSUE TITLE
profile tool adjustments

### ISSUE THREAD

**Issue by olemunch** [sashuk/watsonc#74]
@sashuk 
@mapcentia 
I'm stil not able to run the profile tool from the testsite

But:
It should be possible to draw a profile whithout choosing a chemical or a geological layer or other data (FOHM , potentialekort) 

In that case the script will just return a plot with boreholes

**Comment by sashuk** [comment]
@mapcentia @olemunch Implemented in https://github.com/sashuk/watsonc/commit/f3f8fa2e75c0a2ffdf908fedc24e0cd994acb29a.

@mapcentia please note that the Watsonc Docker image should be rebuilt with the new `profil` Python script (https://github.com/mapcentia/dockerfiles_custom/commit/68f2a3f79d052695b5bc5ffa7367af0a601257c8).

Demo:
![parameters](https://user-images.githubusercontent.com/1390758/62855636-5cceb100-bd25-11e9-973e-f71e4450f9fb.gif)
