### ISSUE TITLE
Wrong coloring of symbols

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#76]
@sashuk 
It seems like max and senest (latest) has been switched 
![image](https://user-images.githubusercontent.com/50234893/62861555-259bd800-bd04-11e9-8866-d0f2c6ad9995.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Fixed in https://github.com/sashuk/watsonc/commit/359758055b5b93b4fea57485313a9fbc852e3daa

Demo:
![coloring](https://user-images.githubusercontent.com/1390758/62868406-2c4c3e80-bd48-11e9-895f-e96c600f3bbc.gif)

**Comment by JacobBirk** [comment]
Thanks. 
Really sorry that you can't work for Martin anymore. You have made a really good job

**Comment by sashuk** [comment]
@JacobBirk Thank you very much!
