### ISSUE TITLE
Load of symbols 

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#77]
Nitrate is selected and adress search is performed, but colored symbols isn’t showed 
![image](https://user-images.githubusercontent.com/50234893/62863192-6695eb80-bd08-11e9-8406-97ecd6b6f609.png)

Ole wonder if Calypso is loading an outdated view

Seems like loading process fails
![image](https://user-images.githubusercontent.com/50234893/62863207-70b7ea00-bd08-11e9-8bcc-a708399f293c.png)

**Comment by sashuk** [comment]
@JacobBirk Could you please specify what behaviour is expected? I've performed the following steps:

1. Selected the layer and chemical in the startup windows;
2. Searched for the address;
3. The address search has shown the result, symbols with chemical indication were kept, so symbols are shown.

Demo:
![layer](https://user-images.githubusercontent.com/1390758/62918569-90b3e000-bdd2-11e9-9eaa-73ba71c3026b.gif)

**Comment by JacobBirk** [comment]
I selected layer and chemical at DK zoom level and made the adress search. Here I would expect synbols with chemical info, but I just got gray symbold

**Comment by sashuk** [comment]
@JacobBirk As you can see in the screencast I have provided before, the chemical display for different boreholes is kept after performing the address search, so could you please specify the actual **before the address search** view of the map (the screencast will be ideal)? Maybe the chemical was selected in the `Data sources and types` menu, but was not applied before the search?

**Comment by JacobBirk** [comment]
@sashuk @mapcentia Martin think that the problem occur because the search bypasses the zoom level that activate the activation of synbols with chemicals. Does that make sense?

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Thank you, that totally makes sense! Fixed in https://github.com/sashuk/watsonc/commit/bdb860ca67ca3e9a65d6f0391d5b67b98aba3025

Demo:
![zoom](https://user-images.githubusercontent.com/1390758/63091469-0a91c800-bf91-11e9-9a28-cffce6676f37.gif)
