### ISSUE TITLE
Map Icons

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#78]
Adjust the location of icon so they don’t overlap 
![image](https://user-images.githubusercontent.com/50234893/62863373-e2903380-bd08-11e9-80f7-b4e6f49215fe.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Fixed in https://github.com/sashuk/watsonc/commit/73923cdcf9f6db019eb96f4d862f8b9cbecf42e6

Demo:
![scale](https://user-images.githubusercontent.com/1390758/62918931-bf7e8600-bdd3-11e9-8048-c83b836b470c.gif)
