### ISSUE TITLE
PayloadTooLargeError: too many parameters

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#8]
When having a lot of plots you'll run into a 413 on the /api/state-snapshots end-point. Can it be send in another form? In a JSON body?
![image](https://user-images.githubusercontent.com/3850918/49587357-e8589c80-f963-11e8-9e37-c233c5221025.png)

**Comment by sashuk** [comment]
@mapcentia Probably there are certain limitation in the Express configuration (like maximum payload size), currently investigating.

**Comment by sashuk** [comment]
@mapcentia Could ypu please provide demo access to the `jupiter` database, so the saving of state snapshots can be tested?

**Comment by sashuk** [comment]
@sashuk Access was provided in email, error was observed

https://github.com/expressjs/body-parser/blob/master/README.md#too-many-parameters

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/a15eadfe457a190814cc37317a8337e68727957c
