### ISSUE TITLE
Boxes overlap each other in startup-wizard

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#80]
The two clickable boxes under “Grundvand” overlap eachother. If you click in the bottom half of the box on top, the box below is chosen. The grey circle on the picture below marks the clickable area.
![image](https://user-images.githubusercontent.com/50234893/62864854-25540a80-bd0d-11e9-8a27-15f3fccc1b4b.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Fixed in https://github.com/sashuk/watsonc/commit/838b61315638fc6c1b17c59d375fb62e7baa5a57

Demo:
![click](https://user-images.githubusercontent.com/1390758/62995101-c79cfb00-be91-11e9-9ed3-6748eec32a14.gif)
