### ISSUE TITLE
changes to data-window

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#81]
During our user test we found that the drag-and-drop function was not obviuos for everybody. Therefore we would like a few changes to this window. On the typable line to the right, “Ny titel” should be changed to “Opret ny”. The save icon next to it should be changed to a plus symbol.
The text “No time series created yet” should be translated to danish, “Ingen tabeller oprettet”.
Below, a help text should be added to guide the user first time he/she is creating a time series. “Opret en ny tabel og træk herefter dine ønskede dataserier over i boksen - så er du i gang.”
When the user has created a timeseries, the help text doesn’t need to appear anymore.
![image](https://user-images.githubusercontent.com/50234893/62865070-c216a800-bd0d-11e9-9513-23c4ee7f1bce.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Implemented in https://github.com/sashuk/watsonc/commit/a41c69997d17c230625fc46dc63e23607a24dd14

Demo:
![data](https://user-images.githubusercontent.com/1390758/62915584-91934480-bdc7-11e9-885e-6b3856a24a2b.gif)
