### ISSUE TITLE
Removing Plotly graphs from dashboards

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#82]
The “Slet” button completly deletes the graph from your profile. Instead the button should be renamed to “Fjern” and a click on the button will remove the graph from the dashboard, but keep it on the users list of created timeseries/profiles.
![image](https://user-images.githubusercontent.com/50234893/62865153-f38f7380-bd0d-11e9-8abb-fabc5d2fbcaf.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Implemented in https://github.com/sashuk/watsonc/commit/158758e8789e0520fc70e7793365a1fc5ef782eb

Demo:
![removing](https://user-images.githubusercontent.com/1390758/62917117-978c2400-bdcd-11e9-8811-db6af32d4c27.gif)
