### ISSUE TITLE
Burgermenu open and close button dissapear

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#83]
When I click on a lot of different things (to try and stress the performance) the Burgermenu-button and the close button dissapears. Example below: Menu is closed and no burgermenu-button = Impossible to open the rightside-menu.
![image](https://user-images.githubusercontent.com/50234893/62865211-26d20280-bd0e-11e9-825b-9182fbd8cfa2.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Fixed in https://github.com/sashuk/watsonc/commit/8e2e194f994b75a7d11eee79b4ae438d76b59f8e

Demo:
![switching](https://user-images.githubusercontent.com/1390758/62925102-2c018100-bde4-11e9-8a52-df92584c58a1.gif)
