### ISSUE TITLE
Row versus Matrix view

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#84]
In the dashboard the chosen viewmode (row or matrix) is currently marked with a white button, while the non-chosen is marked with green. This should be the opposite, so that the green button marks the chosen view.
![image](https://user-images.githubusercontent.com/50234893/62865333-7ca6aa80-bd0e-11e9-82e6-beb75deb5209.png)

**Comment by sashuk** [comment]
@JacobBirk Two buttons are drawn in accordance with the material design concepts (https://material.io/design/interaction/states.html#disabled), which means that we can not click the Matrix view, for example, when it is already active - so, the button for the Matrix view should be **disabled**, which prevents a user from clicking it. Should this design concept be broken anyway?

Demo:
![viewmode](https://user-images.githubusercontent.com/1390758/62865753-d70d2e80-bd41-11e9-8e28-1f977fc96473.gif)

**Comment by JacobBirk** [comment]
@sashuk Ok. Not a big issue. Just seems non-intuitive that the chosen option is faded

**Comment by sashuk** [comment]
@JacobBirk Maybe just to make the faded button to have a black font color to make it more readable then?

Demo:
![color](https://user-images.githubusercontent.com/1390758/62918343-ef2c8e80-bdd1-11e9-9b78-77941dfed24a.gif)

**Comment by JacobBirk** [comment]
Better 🙂
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: 13. august 2019 07:55
Til: sashuk/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [sashuk/watsonc] Row versus Matrix view (#84)


@JacobBirk<https://github.com/JacobBirk> Maybe just to make the faded button to have a black font color to make it more readable then?

Demo:
[color]<https://user-images.githubusercontent.com/1390758/62918343-ef2c8e80-bdd1-11e9-9b78-77941dfed24a.gif>

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Implemented in https://github.com/sashuk/watsonc/commit/7395d627d39c827bebc4b2bed8f03cf4009080d8
