### ISSUE TITLE
Profile tool, top margin?

### ISSUE THREAD

**Issue by olemunch** [sashuk/watsonc#87]
@sashuk 
The margin of the profile graphs behaves stangly. In a small window the profile almost disapears because of the large top and bottom-margin.
The script does not set a margin as far as I can see. Can you figure out why and fix it?

![image](https://user-images.githubusercontent.com/51031638/62932956-77eefe80-bdc1-11e9-99c9-3396a188b24c.png)

**Comment by WatsonC-hub** [comment]
@sashuk 
Adding to the layout object           
           margin=go.Margin(
                                l=50,
                                r=5,
                                b=45,
                                t=5,
                                pad=1
                            ),

solves the problem. Do you prefer defining margin in the script or applying same margin settings as defined in vidi for all other graphs?

Should I just apply changes to the code?

**Comment by sashuk** [comment]
@mapcentia @WatsonC-hub The layout setting was added in the JavaScript code, as the plots layout representation is defined via JavaScript code as well (keeping representation settings in the same place), implemented in https://github.com/sashuk/watsonc/commit/3b326c0da9d97de97f0a94e581eec53afc0e32bb

Demo (before and after):
![diff](https://user-images.githubusercontent.com/1390758/62994402-498b2500-be8e-11e9-9feb-370edd7cb22c.gif)
