### ISSUE TITLE
Assign geological profiles to user profile

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#89]
@sashuk 
Profiles should (like timeseries) be stored on user profiles and not be "global"

**Comment by sashuk** [comment]
@JacobBirk Am I correct that users should not be able to create profiles or time series if they are not authorized?

**Comment by JacobBirk** [comment]
Yes

Jacob
________________________________
Fra: Aleksandr Shumilov <notifications@github.com>
Sendt: Wednesday, August 14, 2019 6:13:44 AM
Til: sashuk/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [sashuk/watsonc] Assign geological profiles to user profile (#89)


@JacobBirk<https://github.com/JacobBirk> Am I correct that users should not be able to create profiles or time series if they are not authorized?

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Implemented in https://github.com/sashuk/watsonc/commit/a973426381265e86f23699e68b5f6a9a201defad

Demo:
![profilesaccess](https://user-images.githubusercontent.com/1390758/63157607-e8a84c00-c049-11e9-889b-9fd604beab30.gif)
