### ISSUE TITLE
Enable touch drag in application

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#9]

**Comment by sashuk** [comment]
@mapcentia Could you please specify if this issue is same as https://github.com/sashuk/vidi/issues/228?

**Comment by mapcentia** [comment]
@sashuk here its draging the measurement to a plot. In Vidi core its sorting in layer tree

**Comment by sashuk** [comment]
@mapcentia Thanks a lot!

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/watsonc/commit/53630003b645119b2fbb425d47306748b8dca5f4


![ezgif com-optimize](https://user-images.githubusercontent.com/1390758/50287532-019e3480-049e-11e9-9cd8-476cd0a43c60.gif)

**Comment by mapcentia** [comment]
@sashuk I can't get touch drag in WatsonC to work. Could you test?

**Comment by sashuk** [comment]
@mapcentia Could you please specify what device does not support drag and drop?

Current `watsonc` codebase was tested in **iPhone 6** (iOS; Google Chrome, Safari), **Nexus 6** (Android; Google Chrome) and **Samsung Galaxy S7** (Android; Google Chrome, Firefox).

**Comment by mapcentia** [comment]
@sashuk Its working in IOS. But there is no visual indication of you're a draging an element.

**Comment by sashuk** [comment]
@mapcentia Got it, thanks! The visual indication will be implemented.

**Comment by sashuk** [comment]
@mapcentia Could you please specify if visualization below is acceptable?

![drag](https://user-images.githubusercontent.com/1390758/50836546-5b817400-1351-11e9-818f-876a5b8a7410.gif)

**Comment by mapcentia** [comment]
@sashuk Looks alright. I'll present it to the client. Closing

**Comment by sashuk** [comment]
@mapcentia Reopened this just not to forget to push this change a llittle bit later

**Comment by sashuk** [comment]
@mapcentia Visualization was added in https://github.com/sashuk/watsonc/commit/3ba142df87e367a4612727d586e616e2358fadf9
