### ISSUE TITLE
Add scroll bar to datamenu

### ISSUE THREAD

**Issue by JacobBirk** [sashuk/watsonc#90]
@sashuk We would like two scroll bars: one for the "Data serier"  and one for "Tidsserier"
. It would make drag&drop easy for items in the bottom of the "data serier"
![image](https://user-images.githubusercontent.com/50234893/62942531-c78cf480-bdd8-11e9-9d69-8bd984de2a6b.png)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Fixed in https://github.com/sashuk/watsonc/commit/d91c75dbba10bae55991b8d0c65fd9bba6a60125

Demo:
![display](https://user-images.githubusercontent.com/1390758/62994098-ca492180-be8c-11e9-84d5-fd1e2392a1d7.gif)
