### ISSUE TITLE
Disable "Water level / Vandstand" from profile menu

### ISSUE THREAD

**Issue by WatsonC-hub** [sashuk/watsonc#91]
@sashuk 
The profile tool is not able to show water level data. We suggest a quick-fix where we remove "Vandstand" from the menu "Valgt datatype"

Alternatively an empty string "" should be given as input to the compound value send to the script,
"Compound":"" - which will prevent the error code 400 and draw a profile without chemicals

**Comment by sashuk** [comment]
@mapcentia @WatsonC-hub Implemented in https://github.com/sashuk/watsonc/commit/6f0b82c734303aae5bb78fb30b7482881ad8601f

Demo:
![level](https://user-images.githubusercontent.com/1390758/62993057-7dfbe280-be88-11e9-885d-e0ddf922aea5.gif)
