### ISSUE TITLE
Small fix for profile-tool

### ISSUE THREAD

**Issue by ksnwatsonc** [sashuk/watsonc#92]
Hey @sashuk 

We have done some slight changes to the profile tool menu, to make the user path more obvious.
Basically, only one step get revealed at a time. First the user types a name for the profile and clicks "Fortsæt" (continue). This opens up for the next step, where the user can make adjustment to buffer, "profilbund" and data type, and draw the profile.

When the user chooses a data type, it should be possible to pick nothing. On the list, this option should be named "Vis uden datatype" and be the first option on the list.

Once the user clicks "Tegn profil", the adjustments above are faded and non-clickable, as the users can not make these changes now.

When the user has drawn the line, the "Fortsæt"-button (continue) gets more visible. The user can also choose to "Fortryd" (undo) the line, and change the adjustments or just re-draw the line.

Once the user clicks "Fortsæt" the models/maps are generated. The user makes his decision and press "Gem og afslut" (Save and continue). This will add the newly created profile to the users list, and the profile tool steps will close down to show only the first step again.

![Web 1920 – 1](https://user-images.githubusercontent.com/50231643/63079504-d392c680-bf3e-11e9-856c-901f546e8827.png)
![Web 1920 – 5](https://user-images.githubusercontent.com/50231643/63079505-d392c680-bf3e-11e9-9beb-d2db3109bff9.png)
![Web 1920 – 7](https://user-images.githubusercontent.com/50231643/63079506-d392c680-bf3e-11e9-9e38-1ce70cfac3f8.png)
![Web 1920 – 9](https://user-images.githubusercontent.com/50231643/63079507-d392c680-bf3e-11e9-822a-182429d2f3c9.png)
![Web 1920 – 10](https://user-images.githubusercontent.com/50231643/63079508-d392c680-bf3e-11e9-98ba-7d2885232cf6.png)
![Web 1920 – 11](https://user-images.githubusercontent.com/50231643/63079509-d42b5d00-bf3e-11e9-8ff8-e97bd91e541a.png)

**Comment by sashuk** [comment]
@mapcentia @ksnwatsonc Implemented in https://github.com/sashuk/watsonc/commit/b5c2b5a10fc8e395250123b6c62ed112b64d0df6

Demo:
![profiles](https://user-images.githubusercontent.com/1390758/63089865-e8497b80-bf8b-11e9-820c-0400d6b33b6f.gif)
