### ISSUE TITLE
Download button is not responding properly

### ISSUE THREAD

**Issue by ksnwatsonc** [sashuk/watsonc#93]
When trying to download a timeseries, nothing happens when clicking the Download button.

**Comment by sashuk** [comment]
@ksnwatsonc Could you please specify what time series you tried to download? Chemicals or water time series seem to download correctly:

![file](https://user-images.githubusercontent.com/1390758/63085623-86374900-bf80-11e9-9a0a-2f9cadf4c4e2.gif)

**Comment by ksnwatsonc** [comment]
@sashuk and @JacobBirk (who also had the issue) I have tested it again and seem to have found the problem. I have to be logged in with my user profile to be able to download it. Once I'm logged in it works fine on Chrome. I've tried the same in Edge and download doesn't work whether i'm logged in or not. Maybe a problem with the specific browser again?

**Comment by sashuk** [comment]
@ksnwatsonc So, when you are not logged in (in Chrome), time series are not downloaded?

I've checked the Firefox as well, seems like this is the issue of only the Microsoft Edge indeed.

**Comment by ksnwatsonc** [comment]
@sashuk Exactly. So I don't think it's really an issue, as every user, once we release, should have their own user profile to gain access. Right, @JacobBirk ?

One more related issue. Below is an example of a project with 10 timeseries in the same graph. When I try to download it, I get an error message, _"Error occured while generating plot XSLS file"_. Can you figure out what causes this? 
<img width="764" alt="Norge projekt" src="https://user-images.githubusercontent.com/50231643/63090499-c20be780-bf5b-11e9-8a8f-f88a1539f20b.PNG">

**Comment by sashuk** [comment]
@ksnwatsonc According to https://github.com/sashuk/watsonc/issues/89, yes, every user has its own profiles!

I will check the case for heavy time series then!

**Comment by sashuk** [comment]
@ksnwatsonc The real reason was that Excel sheets had the same name (as several intakes from single borehole were used) which was causing the error - now it is ensured that they have unique names, fixed in https://github.com/sashuk/watsonc/commit/f5e443732c91bf4e0281e04f5b16eec5e269688e
